In [ ]:
# Simple RAG Agent

# Load the pdf files and split them into chunks

In [1]:
from langchain_community.document_loaders import DirectoryLoader
from langchain_community.document_loaders import PyMuPDFLoader

directory_loader = DirectoryLoader("data", glob="**/*.pdf", loader_cls=PyMuPDFLoader)

docs = directory_loader.load()

print(docs)

[Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 0}, page_content='NBER WORKING PAPER SERIES\nHOW PEOPLE USE CHATGPT\nAaron Chatterji\nThomas Cunningham\nDavid J. Deming\nZoe Hitzig\nChristopher Ong\nCarl Yan Shan\nKevin Wadman\nWorking Paper 34255\nhttp://www.nber.org/papers/w34255\nNATIONAL BUREAU OF ECONOMIC RESEARCH\n1050 Massachusetts Avenue\nCambridge, MA 02138\nSeptember 2025\nWe acknowledge help and comments from Joshua Achiam, Hemanth Asirvatham, Ryan \nBeiermeister, Rachel Brown, Cassandra Duchan Solis, Jason Kwon, Elliott Mokski, Kevin Rao, \nHarrison Satcher, Gawesha Weeratunga, Hannah Wong, and Analytics & Insights team. We \nespecially thank Tyna Eloundou and Pamela Mishkin who in several ways laid the foundation for \nthis work. This study was approved by Harvard IRB (IRB25-0983). A repository containing all \ncode run to produce the analyses in this paper is available on request. The views expressed herein \nare those of the authors and do not necessarily reflect the views of the National Bureau of \nEconomic Research.\nAt least one co-author has disclosed additional relationships of potential relevance for this research. \nFurther information is available online at http://www.nber.org/papers/w34255\nNBER working papers are circulated for discussion and comment purposes. They have not been \npeer-reviewed or been subject to the review by the NBER Board of Directors that accompanies \nofficial NBER publications.\n© 2025 by Aaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, \nCarl Yan Shan, and Kevin Wadman. All rights reserved. Short sections of text, not to exceed two \nparagraphs, may be quoted without explicit permission provided that full credit, including © \nnotice, is given to the source.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='How People Use ChatGPT\nAaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, Carl\nYan Shan, and Kevin Wadman\nNBER Working Paper No. 34255\nSeptember 2025\nJEL No. J01, O3, O4\nABSTRACT\nDespite the rapid adoption of LLM chatbots, little is known about how they are used. We \ndocument the growth of ChatGPT’s consumer product from its launch in November 2022 \nthrough July 2025, when it had been adopted by around 10% of the world’s adult population. \nEarly adopters were disproportionately male but the gender gap has narrowed dramatically, and \nwe find higher growth rates in lower-income countries. Using a privacy-preserving automated \npipeline, we classify usage patterns within a representative sample of ChatGPT conversations. \nWe find steady growth in work-related messages but even faster growth in non-work-related \nmessages, which have grown from 53% to more than 70% of all usage. Work usage is more \ncommon for educated users in highly-paid professional occupations. We classify messages by \nconversation topic and find that “Practical Guidance,” “Seeking Information,” and “Writing” are \nthe three most common topics and collectively account for nearly 80% of all conversations. \nWriting dominates work-related tasks, highlighting chatbots’ unique ability to generate digital \noutputs compared to traditional search engines. Computer programming and self-expression both \nrepresent relatively small shares of use. Overall, we find that ChatGPT provides economic value \nthrough decision support, which is especially important in knowledge-intensive jobs.\nAaron Chatterji\nDuke University\nFuqua School of Business \nand OpenAI\nronnie@duke.edu\nThomas Cunningham \nOpenAI\ntom.cunningham@gmail.com\nDavid J. Deming\nHarvard University\nHarvard Kennedy School \nand NBER\ndavid_deming@harvard.edu\nZoe Hitzig\nOpenAI\nand Harvard Society of Fellows\nzhitzig@g.harvard.edu\nChristopher Ong\nHarvard University\nand OpenAI\nchristopherong@hks.harvard.edu\nCarl Yan Shan\nOpenAI\ncshan@openai.com\nKevin Wadman\nOpenAI\nkevin.wadman@c-openai.com'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='1\nIntroduction\nChatGPT launched in November 2022. By July 2025, 18 billion messages were being sent each week\nby 700 million users, representing around 10% of the global adult population.1 For a new technology,\nthis speed of global diffusion has no precedent (Bick et al., 2024).\nThis paper studies consumer usage of ChatGPT, the first mass-market chatbot and likely the\nlargest.2 ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence (AI)\ndeveloped over the last decade and generally considered to represent an acceleration in AI capabilities.3\nThe sudden growth in LLM abilities and adoption has intensified interest in the effects of artificial\nintelligence on economic growth (Acemoglu, 2024; Korinek and Suh, 2024); employment (Eloundou\net al., 2025); and society (Kulveit et al., 2025). However, despite the rapid adoption of LLMs, there\nis limited public information on how they are used. A number of surveys have measured self-reported\nadoption of LLMs (Bick et al., 2024; Pew Research Center, 2025); however there are reasons to expect\nbias in self-reports (Ling and Imas, 2025), and none of these papers have been able to directly track\nthe quantity or nature of chatbot conversations.\nTwo recent papers do report statistics on chatbot conversations, classified in a variety of ways\n(Handa et al., 2025; Tomlinson et al., 2025). We build on this work in several respects. First, the pool\nof users on ChatGPT is far larger, meaning we expect our data to be a closer approximation to the\naverage chatbot user.4 Second, we use automated classifiers to report on the types of messages that\nusers send using new classification taxonomies relative to the existing literature. Third, we report the\ndiffusion of chatbot use across populations and the growth of different types of usage within cohorts.\nFourth, we use a secure data clean room protocol to analyze aggregated employment and education\ncategories for a sample of our users, lending new insights about differences in the types of messages\nsent by different groups while protecting user privacy.\nOur primary sample is a random selection of messages sent to ChatGPT on consumer plans (Free,\nPlus, Pro) between May 2024 and June 2025.5\nMessages from the user to chatbot are classified\nautomatically using a number of different taxonomies: whether the message is used for paid work,\nthe topic of conversation, and the type of interaction (asking, doing, or expressing), and the O*NET\ntask the user is performing. Each taxonomy is defined in a prompt passed to an LLM, allowing us to\nclassify messages without any human seeing them. We give the text of most prompts in Appendix A\nalong with details about how the prompts were validated in Appendix B.6 The classification pipeline is\nprotected by a series of privacy measures, detailed below, to ensure no leakage of sensitive information\nduring the automated analysis. In a secure data clean room, we relate taxonomies of messages to\naggregated employment and education categories.\nTable 1 shows the growth in total message volume for work and non-work usage. Both types of\n1Reuters (2025), Roth (2025)\n2Bick et al. (2024) report that 28% of US adults used ChatGPT in late 2024, higher than any other chatbot.\n3We use the term LLM loosely here and give more details in the following section.\n4Wiggers (2025) reports estimates that in April 2025 ChatGPT was receiving more than 10 times as many visitors\nas either Claude or Copilot.\n5Our sample includes the three consumer plans (Free, Plus, or Pro). OpenAI also offers a variety of other ChatGPT\nplans (Business fka. Teams, Enterprise, Education), which we do not include in our sample.\n6Our classifiers take into account not just the randomly-selected user message, but also a portion of the preceding\nmessages in that conversation.\n1'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='Month\nNon-Work (M)\n(%)\nWork (M)\n(%)\nTotal Messages (M)\nJun 2024\n238\n53%\n213\n47%\n451\nJun 2025\n1,911\n73%\n716\n27%\n2,627\nTable 1: ChatGPT daily message counts (millions), broken down by likely work-related or non-work-related.\nTotal daily counts are exact measurements of message volume from all consumer plans. Daily counts of work\nand non-work related messages are estimated by classifying a random sample of conversations from that day.\nSampling is done to exclude users who opt-out of sharing their messages for model training, users who self-\nreport their age as under 18, logged-out users, deleted conversations, and accounts which have been deactivated\nor banned (details available in Section 3). Reported values are 7-day averages (to smooth weekly fluctuation)\nending on the 26th of June 2024 and 26th of June 2025.\nmessages have grown continuously, but non-work messages have grown faster and now represent more\nthan 70% of all consumer ChatGPT messages. While most economic analysis of AI has focused on its\nimpact on productivity in paid work, the impact on activity outside of work (home production) is on a\nsimilar scale and possibly larger. The decrease in the share of work-related messages is primarily due to\nchanging usage within each cohort of users rather than a change in the composition of new ChatGPT\nusers. This finding is consistent with Collis and Brynjolfsson (2025), who use choice experiments to\nuncover willingness-to-pay for generative AI and estimate a consumer surplus of at least $97 billion\nin 2024 alone in the US.\nWe next report on a classification of messages using a taxonomy developed at OpenAI for un-\nderstanding product usage (“conversation classifier”). Nearly 80% of all ChatGPT usage falls into\nthree broad categories, which we call Practical Guidance, Seeking Information, and Writing. Practical\nGuidance is the most common use case and includes activities like tutoring and teaching, how-to\nadvice about a variety of topics, and creative ideation.7 Seeking Information includes searching for\ninformation about people, current events, products, and recipes, and appears to be a very close sub-\nstitute for web search. Writing includes the automated production of emails, documents and other\ncommunications, but also editing, critiquing, summarizing, and translating text provided by the user.\nWriting is the most common use case at work, accounting for 40% of work-related messages on average\nin June 2025. About two-thirds of all Writing messages ask ChatGPT to modify user text (editing,\ncritiquing, translating, etc.) rather than creating new text from scratch. About 10% of all messages\nare requests for tutoring or teaching, suggesting that education is a key use case for ChatGPT.\nTwo of our findings stand in contrast to other work. First, we find the share of messages related\nto computer coding is relatively small: only 4.2% of ChatGPT messages are related to computer\nprogramming, compared to 33% of work-related Claude conversations Handa et al. (2025).8 Second, we\nfind the share of messages related to companionship or social-emotional issues is fairly small: only 1.9%\nof ChatGPT messages are on the topic of Relationships and Personal Reflection and 0.4% are related\n7The difference between Practical Guidance and Seeking Information is that the former is highly customized to the\nuser and can be adapted based on conversation and follow-up, whereas the latter is factual information that should be\nthe same for all users. For example, users interested in running might ask ChatGPT for the Boston Marathon qualifying\ntimes by age and gender (Seeking Information), or they might ask for a customized workout plan that matches their\ngoals and current level of fitness (Practical Guidance).\n8Handa et al. (2025) report that 37% of conversations are mapped to a “computer and mathematical” occupation\ncategory, and their Figure 12 shows 30% or more of all imputed tasks are programming or IT-related. We believe the\ndiscrepancy is partly due to the difference in types of users between Claude and ChatGPT, additionally Handa et al.\n(2025) only includes queries that ”possibly involve an occupational task”.\n2'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 4}, page_content='to Games and Role Play. In contrast, Zao-Sanders (2025) estimates that Therapy/Companionship is\nthe most prevalent use case for generative AI.9\nWe also document several important facts about demographic variation in ChatGPT usage. First,\nwe show evidence that the gender gap in ChatGPT usage has likely narrowed considerably over time,\nand may have closed completely. In the few months after ChatGPT was released about 80% of active\nusers had typically masculine first names.10 However, that number declined to 48% as of June 2025,\nwith active users slightly more likely to have typically feminine first names. Second, we find that\nnearly half of all messages sent by adults were sent by users under the age of 26, although age gaps\nhave narrowed somewhat in recent months. Third, we find that ChatGPT usage has grown relatively\nfaster in low- and middle-income countries over the last year. Fourth, we find that educated users and\nusers in highly-paid professional occupations are substantially more likely to use ChatGPT for work.\nWe introduce a new taxonomy to classify messages according to the kind of output the user is\nseeking, using a simple rubric that we call Asking, Doing, or Expressing.11\nAsking is when the\nuser is seeking information or clarification to inform a decision, corresponding to problem-solving\nmodels of knowledge work (e.g., Garicano (2000); Garicano and Rossi-Hansberg (2006); Carnehl and\nSchneider (2025); Ide and Talamas (2025)). Doing is when the user wants to produce some output\nor perform a particular task, corresponding to classic task-based models of work (e.g., Autor et al.\n(2003)). Expressing is when the user is expressing views or feelings but not seeking any information or\naction. We estimate that about 49% of messages are Asking, 40% are Doing, and 11% are Expressing.\nHowever, as of July 2025 about 56% of work-related messages are classified as Doing (e.g., performing\njob tasks), and nearly three-quarters of those are Writing tasks. The relative frequency of writing-\nrelated conversations is notable for two reasons. First, writing is a task that is common to nearly all\nwhite-collar jobs, and good written communication skills are among the top “soft” skills demanded by\nemployers (National Association of Colleges and Employers, 2024). Second, one distinctive feature of\ngenerative AI, relative to other information technologies, is its ability to produce long-form outputs\nsuch as writing and software code.\nWe also map message content to work activities using the Occupational Information Network\n(O*NET), a survey of job characteristics supported by the U.S. Department of Labor. We find that\nabout 81% of work-related messages are associated with two broad work activities: 1) obtaining,\ndocumenting, and interpreting information; and 2) making decisions, giving advice, solving problems,\nand thinking creatively. Additionally, we find that the work activities associated with ChatGPT usage\nare highly similar across very different kinds of occupations. For example, the work activities Getting\nInformation and Making Decisions and Solving Problems are in the top five of message frequency in\nnearly all occupations, ranging from management and business to STEM to administrative and sales\noccupations.\nOverall, we find that information-seeking and decision support are the most common ChatGPT\nuse cases in most jobs. This is consistent with the fact that almost half of all ChatGPT usage is\neither Practical Guidance or Seeking Information. We also show that Asking is growing faster than\n9Zao-Sanders (2025) is based on a manual collection and labeling of online resources (Reddit, Quora, online articles),\nand so we believe it likely resulted in an unrepresentative distribution of use cases.\n10Among those with names commonly associated with a particular gender.\n11Appendix A gives the full prompt text and Appendix B gives detail about how the prompts were validated against\npublic conversation data.\n3'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 5}, page_content='Doing, and that Asking messages are consistently rated as having higher quality both by a classifier\nthat measures user satisfaction and from direct user feedback.\nHow does ChatGPT provide economic value, and for whom is its value the greatest? We argue that\nChatGPT likely improves worker output by providing decision support, which is especially important in\nknowledge-intensive jobs where better decision-making increases productivity (Deming, 2021; Caplin et\nal., 2023). This explains why Asking is relatively more common for educated users who are employed\nin highly-paid, professional occupations.\nOur findings are most consistent with Ide and Talamas\n(2025), who develop a model where AI agents can serve either as co-workers that produce output or\nas co-pilots that give advice and improve the productivity of human problem-solving.\n2\nWhat is

In [2]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=750, chunk_overlap=100)
split_docs = text_splitter.split_documents(docs)

print(split_docs)

len(split_docs)

[Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 0}, page_content='NBER WORKING PAPER SERIES\nHOW PEOPLE USE CHATGPT\nAaron Chatterji\nThomas Cunningham\nDavid J. Deming\nZoe Hitzig\nChristopher Ong\nCarl Yan Shan\nKevin Wadman\nWorking Paper 34255\nhttp://www.nber.org/papers/w34255\nNATIONAL BUREAU OF ECONOMIC RESEARCH\n1050 Massachusetts Avenue\nCambridge, MA 02138\nSeptember 2025\nWe acknowledge help and comments from Joshua Achiam, Hemanth Asirvatham, Ryan \nBeiermeister, Rachel Brown, Cassandra Duchan Solis, Jason Kwon, Elliott Mokski, Kevin Rao, \nHarrison Satcher, Gawesha Weeratunga, Hannah Wong, and Analytics & Insights team. We \nespecially thank Tyna Eloundou and Pamela Mishkin who in several ways laid the foundation for \nthis work. This study was approved by Harvard IRB (IRB25-0983). A repository containing all'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 0}, page_content='this work. This study was approved by Harvard IRB (IRB25-0983). A repository containing all \ncode run to produce the analyses in this paper is available on request. The views expressed herein \nare those of the authors and do not necessarily reflect the views of the National Bureau of \nEconomic Research.\nAt least one co-author has disclosed additional relationships of potential relevance for this research. \nFurther information is available online at http://www.nber.org/papers/w34255\nNBER working papers are circulated for discussion and comment purposes. They have not been \npeer-reviewed or been subject to the review by the NBER Board of Directors that accompanies \nofficial NBER publications.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 0}, page_content='official NBER publications.\n© 2025 by Aaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, \nCarl Yan Shan, and Kevin Wadman. All rights reserved. Short sections of text, not to exceed two \nparagraphs, may be quoted without explicit permission provided that full credit, including © \nnotice, is given to the source.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='How People Use ChatGPT\nAaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, Carl\nYan Shan, and Kevin Wadman\nNBER Working Paper No. 34255\nSeptember 2025\nJEL No. J01, O3, O4\nABSTRACT\nDespite the rapid adoption of LLM chatbots, little is known about how they are used. We \ndocument the growth of ChatGPT’s consumer product from its launch in November 2022 \nthrough July 2025, when it had been adopted by around 10% of the world’s adult population. \nEarly adopters were disproportionately male but the gender gap has narrowed dramatically, and \nwe find higher growth rates in lower-income countries. Using a privacy-preserving automated'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='we find higher growth rates in lower-income countries. Using a privacy-preserving automated \npipeline, we classify usage patterns within a representative sample of ChatGPT conversations. \nWe find steady growth in work-related messages but even faster growth in non-work-related \nmessages, which have grown from 53% to more than 70% of all usage. Work usage is more \ncommon for educated users in highly-paid professional occupations. We classify messages by \nconversation topic and find that “Practical Guidance,” “Seeking Information,” and “Writing” are \nthe three most common topics and collectively account for nearly 80% of all conversations. \nWriting dominates work-related tasks, highlighting chatbots’ unique ability to generate digital'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='Writing dominates work-related tasks, highlighting chatbots’ unique ability to generate digital \noutputs compared to traditional search engines. Computer programming and self-expression both \nrepresent relatively small shares of use. Overall, we find that ChatGPT provides economic value \nthrough decision support, which is especially important in knowledge-intensive jobs.\nAaron Chatterji\nDuke University\nFuqua School of Business \nand OpenAI\nronnie@duke.edu\nThomas Cunningham \nOpenAI\ntom.cunningham@gmail.com\nDavid J. Deming\nHarvard University\nHarvard Kennedy School \nand NBER\ndavid_deming@harvard.edu\nZoe Hitzig\nOpenAI\nand Harvard Society of Fellows\nzhitzig@g.harvard.edu\nChristopher Ong\nHarvard University\nand OpenAI'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='and Harvard Society of Fellows\nzhitzig@g.harvard.edu\nChristopher Ong\nHarvard University\nand OpenAI\nchristopherong@hks.harvard.edu\nCarl Yan Shan\nOpenAI\ncshan@openai.com\nKevin Wadman\nOpenAI\nkevin.wadman@c-openai.com'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='1\nIntroduction\nChatGPT launched in November 2022. By July 2025, 18 billion messages were being sent each week\nby 700 million users, representing around 10% of the global adult population.1 For a new technology,\nthis speed of global diffusion has no precedent (Bick et al., 2024).\nThis paper studies consumer usage of ChatGPT, the first mass-market chatbot and likely the\nlargest.2 ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence (AI)\ndeveloped over the last decade and generally considered to represent an acceleration in AI capabilities.3\nThe sudden growth in LLM abilities and adoption has intensified interest in the effects of artificial'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='intelligence on economic growth (Acemoglu, 2024; Korinek and Suh, 2024); employment (Eloundou\net al., 2025); and society (Kulveit et al., 2025). However, despite the rapid adoption of LLMs, there\nis limited public information on how they are used. A number of surveys have measured self-reported\nadoption of LLMs (Bick et al., 2024; Pew Research Center, 2025); however there are reasons to expect\nbias in self-reports (Ling and Imas, 2025), and none of these papers have been able to directly track\nthe quantity or nature of chatbot conversations.\nTwo recent papers do report statistics on chatbot conversations, classified in a variety of ways\n(Handa et al., 2025; Tomlinson et al., 2025). We build on this work in several respects. First, the pool'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='of users on ChatGPT is far larger, meaning we expect our data to be a closer approximation to the\naverage chatbot user.4 Second, we use automated classifiers to report on the types of messages that\nusers send using new classification taxonomies relative to the existing literature. Third, we report the\ndiffusion of chatbot use across populations and the growth of different types of usage within cohorts.\nFourth, we use a secure data clean room protocol to analyze aggregated employment and education\ncategories for a sample of our users, lending new insights about differences in the types of messages\nsent by different groups while protecting user privacy.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='sent by different groups while protecting user privacy.\nOur primary sample is a random selection of messages sent to ChatGPT on consumer plans (Free,\nPlus, Pro) between May 2024 and June 2025.5\nMessages from the user to chatbot are classified\nautomatically using a number of different taxonomies: whether the message is used for paid work,\nthe topic of conversation, and the type of interaction (asking, doing, or expressing), and the O*NET\ntask the user is performing. Each taxonomy is defined in a prompt passed to an LLM, allowing us to\nclassify messages without any human seeing them. We give the text of most prompts in Appendix A\nalong with details about how the prompts were validated in Appendix B.6 The classification pipeline is'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='protected by a series of privacy measures, detailed below, to ensure no leakage of sensitive information\nduring the automated analysis. In a secure data clean room, we relate taxonomies of messages to\naggregated employment and education categories.\nTable 1 shows the growth in total message volume for work and non-work usage. Both types of\n1Reuters (2025), Roth (2025)\n2Bick et al. (2024) report that 28% of US adults used ChatGPT in late 2024, higher than any other chatbot.\n3We use the term LLM loosely here and give more details in the following section.\n4Wiggers (2025) reports estimates that in April 2025 ChatGPT was receiving more than 10 times as many visitors\nas either Claude or Copilot.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='as either Claude or Copilot.\n5Our sample includes the three consumer plans (Free, Plus, or Pro). OpenAI also offers a variety of other ChatGPT\nplans (Business fka. Teams, Enterprise, Education), which we do not include in our sample.\n6Our classifiers take into account not just the randomly-selected user message, but also a portion of the preceding\nmessages in that conversation.\n1'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='Month\nNon-Work (M)\n(%)\nWork (M)\n(%)\nTotal Messages (M)\nJun 2024\n238\n53%\n213\n47%\n451\nJun 2025\n1,911\n73%\n716\n27%\n2,627\nTable 1: ChatGPT daily message counts (millions), broken down by likely work-related or non-work-related.\nTotal daily counts are exact measurements of message volume from all consumer plans. Daily counts of work\nand non-work related messages are estimated by classifying a random sample of conversations from that day.\nSampling is done to exclude users who opt-out of sharing their messages for model training, users who self-\nreport their age as under 18, logged-out users, deleted conversations, and accounts which have been deactivated'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='or banned (details available in Section 3). Reported values are 7-day averages (to smooth weekly fluctuation)\nending on the 26th of June 2024 and 26th of June 2025.\nmessages have grown continuously, but non-work messages have grown faster and now represent more\nthan 70% of all consumer ChatGPT messages. While most economic analysis of AI has focused on its\nimpact on productivity in paid work, the impact on activity outside of work (home production) is on a\nsimilar scale and possibly larger. The decrease in the share of work-related messages is primarily due to\nchanging usage within each cohort of users rather than a change in the composition of new ChatGPT'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='changing usage within each cohort of users rather than a change in the composition of new ChatGPT\nusers. This finding is consistent with Collis and Brynjolfsson (2025), who use choice experiments to\nuncover willingness-to-pay for generative AI and estimate a consumer surplus of at least $97 billion\nin 2024 alone in the US.\nWe next report on a classification of messages using a taxonomy developed at OpenAI for un-\nderstanding product usage (“conversation classifier”). Nearly 80% of all ChatGPT usage falls into\nthree broad categories, which we call Practical Guidance, Seeking Information, and Writing. Practical\nGuidance is the most common use case and includes activities like tutoring and teaching, how-to'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='Guidance is the most common use case and includes activities like tutoring and teaching, how-to\nadvice about a variety of topics, and creative ideation.7 Seeking Information includes searching for\ninformation about people, current events, products, and recipes, and appears to be a very close sub-\nstitute for web search. Writing includes the automated production of emails, documents and other\ncommunications, but also editing, critiquing, summarizing, and translating text provided by the user.\nWriting is the most common use case at work, accounting for 40% of work-related messages on average\ni

200

# Create embeddings

In [3]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

In [4]:
# create Qdrant Vector Store
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance,VectorParams

client = QdrantClient(":memory:")

client.create_collection(
    collection_name="rag_collection_name",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

vector_store = QdrantVectorStore(
    client=client,
    collection_name="rag_collection_name",
    embedding=embeddings,
)

In [5]:
# Add documents to the vector store
vector_store.add_documents(documents=split_docs)

['f2b46e02ccb541708d1cde56d0a2f37c',
 'e13ef289404f44bb986dec8da8682768',
 'b8e21594e83145ddb9dee04f6a315a5e',
 '3b04dd0752a9451a8e87b5bf85b8686a',
 '6ac6e1fe7ec9461badb8c25c3df165a4',
 '727ec63c456d44bbbc2bb96ae0d2d2e9',
 '619c9771c8a945c6b8177ff2ec5c3eb6',
 '3c0b9b65e16a4cc393b961ad237c653f',
 'ba5d22fa47f44339b4a828fdcd3e4f0f',
 '66b3bf9f6ee141ac8cf2923fcf7bdcc3',
 '96d6b69291354c2787ca317e2e7329a0',
 '0004ca79a9a8456190152f2f9f49fbd5',
 'bfdefd26cc584f55b8f70457db3b8445',
 'a04745d00d8b406faa3397b30cba2991',
 '38cf02f19c4e4f34a622378b4b517432',
 '7be6d8836a254c46af42994254cc21dd',
 'f67f700ee5554b45bdf048419abee92c',
 '3e0c247a7b7549f48427748529011211',
 '26285c514eb846d58a75eb896f184415',
 '3672870ca6d74fcb886c6f5bf9efc5cf',
 'e144e2510f20445792844a7c26a136f3',
 '13188c47407947bca9beaa4f41195911',
 'd5ac4032797e4dafa0144c7f2e936080',
 '8a56b2574483452ca760015496589399',
 '18dd442db0b844d38f302a2e2a793ce7',
 '89ecac2f97e54b5ab0f5682a85181bd1',
 '52365729f863430d8b9d3db26504a61b',
 '498d0c09fd824d29b383cb8554fa289e',
 '7cfdac3738834f93a1984fd5fe648a8e',
 'b0f4ea8d784f480f942d00d9c869dcda',
 'ed6d77d22f74479aa06e8beb33f2748a',
 'a993a5e98d6641ba90b62cbdf560a5e5',
 '64b7576a2ecf4663aa475e5bdde5a001',
 '2d8367abfe7b464aa2166ab0e0bb1026',
 '4557bbcc020c48f3ae039f77be570fb1',
 '4c0c0018823d4371a3f656cb687b75c1',
 '486f4a0bdfeb48978527180c248ca63e',
 'd66a8b004ee9444ca078ef68c2ceb881',
 '88d2ce08365b440887e0505cd1f2b219',
 '36696e678cea4eac8de8df9904fb35f7',
 '685fba39ea7642f0aaeba977b87e5057',
 '492120c2da304e29a43a38b2c18126a7',
 'c67d647f83504aa2910ff2cdea5fc75f',
 'e7908cea62c749e585097450511e15df',
 'd7befd32564d4d1aa18ca4374d4777eb',
 '54544f49cb0c4b08b985fde3e07d92bf',
 'df261db09b4149ef8b0f61399b14b6af',
 'bced8cc30ee045048a2f1827179f060a',
 '4528d0f86560418b8c8953cd3c5e7c99',
 'e5df95c8b5cc47f093bb702e673b1f5d',
 'c550552145564804b35ff149557f728b',
 '4f4f51fc8bb24fba838d8e9609c6cd4d',
 'f0f3aaea78f34fe2bfbfae45e35b4963',
 '7927b014c55d40c1a0acf41935aa6330',
 '6a3315b928964153b44bdf1afe5a15e8',
 '5dc93105c7974de5ad444de8e59304ab',
 'fd75d537a81847efbf9f98352c4e03cd',
 '2e322ac9b9e14e478ba1d2ad8f17c2ad',
 '7c63d83f1967458ba16b39dcbf40e7d4',
 'f3e71b2840d7451987c3f6c437a9702a',
 'c74681247a1844d8bc8756d7c995453f',
 'e6b72b0506b34bc087cb9f666d82daa4',
 'd12a9fe012124f5bbf7264d56a38aca5',
 '9ffb3be0a36d4c1eba1f267c9ff23658',
 '2d8b8d43118d4a828ad3eb46e66cdca3',
 '2dbb103d77aa43f8af0b5ddf6a0ba0c1',
 'a34f75ca0c224b88910e8db9a5afed71',
 'a79bb2360eec4233b14809e20336e5bd',
 '8ad7f3946d9f41e59be0fb1fbcfa72c6',
 '306a06dfc55e48619c5a6b91479bb6b3',
 '9cca8a91a87545d09a3a34bfa1e54b66',
 'd4b1551c90724965a6aba376bdec73a8',
 'cdb241b1d5854be0991e4a9bce654548',
 'bf88004fc89c415ca74126e6572be8c1',
 'a470ebbe2352439f9e793cfc12eb6500',
 '3cbcdfef55014353a5d5049a2e1752e6',
 'bfd80d2ce4c5413d9e1ca6880cb5ecb5',
 'e730c5315a1c4e158b8e80195bc1e939',
 '2252adaa06ce42da9819797a6bff2bc9',
 '23b9006f87ec40abb2a3838176ef8886',
 '15f3b43dd5714258921e5c93ebc59abd',
 '654616f62d654f66a1b209b6af99b6d6',
 '455bd49004dd4217be80a20060611729',
 '2398e6278b0142a7a34738546be9546b',
 '345cf3f41dd64fce8d0cb0be857dcde0',
 '9abfbbd8e22745a298d3d683135e898a',
 '7d0824dbe1de4287a1aaf1a1e849b495',
 'edd884d3ea8746cdbc942904ff4121e5',
 '842f0359503f43d0a8359c906cf70611',
 '51d16c1d019b48998c5746701b633681',
 'aed0e253bbce47c2be92a48c06aa1619',
 '70611eec8f6e4a74817251620284ed19',
 '437fc384533747d6b3287de5040ee67c',
 'ab00e7b3a01c4a2ea5752f446cf1e70a',
 '5a506a205c1b488aaa4671955eb38631',
 'b2a8594d5cae4bfda2937a2a8ec398bb',
 '36437a808f564fb48eb867dc9c7010ab',
 '5e87e91319994e52bb21d1b20ed01678',
 '7be9f350514f446f99eeb83daf8b4bb2',
 '2e2a077011b24ae5878c6cedbfd473ba',
 'bb4a6f7e0d554b5b83c6ebf1834fdcc6',
 '92f0b947a72d401f841810c3b1ac11f7',
 'eb00fd07af474217b7ada8987d0543f1',
 '68976bf073bf491b9ede5f344d7e09c2',
 '01ffea1fa7b64fc29ec8d2c67cc65f09',
 '6b062ee9f59644b3bccda187138aad51',
 '1eac9ccc4fe648a793cb74f1d3c33b97',
 'd5b8a9b592d649e0b8446f94d623a26a',
 '18ce5498b16c4a5d9bb7706f498c406f',
 '18ff1817cc3b44e8a90fe3458b392b8f',
 '0e3f282147e34b1cbc37994710ac2b1a',
 '26a632f1aae34184b1cc975f9af12e0d',
 'f3f3d67a7c3d40afa6728bba55053915',
 '0977838a2fde43f0b05d1279dc41a138',
 '26a26cf987f2437895af81948da10378',
 '6b45c1b25f0d4d7780f7529b935f4e5c',
 '65a544ab405d49a5ad69d68a32b9950b',
 '06cdb6a720d9478eadbcfd8951290d8f',
 'cf5c1b57eb3a49faa8f4091ec182609e',
 'ef928c0975a94cb38d03e0d2c6579881',
 '18caa2bdf1e5421892c9d4a7e17583ad',
 '2d2ccc5331464933bd62b5e9f92324ec',
 '1203f0a6c71948d69a04c2bcc71da459',
 'a32ad0033688481594fdb65b2b52a55e',
 '5c0bb272920f41c8aabc0b460654a4b8',
 '7b271e1c6d39488b8a444bdf4cc8c1c6',
 'fd6a810fe322413099550637958dd832',
 '435a63791f0a4dc6a5515c9f90593b1d',
 'e56dfee6862743a3ae603dd684fb40df',
 'c31766d2ac8f47e29018a447452bbf93',
 'f4efa886d4a348a09123422f07d0e7ca',
 '38880520d1e54e94aada10795de77cb8',
 '0daa44760201466b8c5178e8c2ad0f49',
 '37cc57619c624d58a799280775b83e6e',
 '0db20db9339e4bccb774a76864d0dd75',
 'fa54ff9541114ae8a3ba671c86134f68',
 'ee070ab9ddfa46fd8a272a65f611552a',
 '1e8d69c4e4794738bdf24ee96a146369',
 'f1c97f30fdd94a848f388207bdae4047',
 'c9bb3737937f49d8a313cc774b5115c4',
 '43acfb90888e40bb9f48cbaaf143763a',
 '933c393b0f13445f9c8c7f7eea991375',
 '3a1ba0e173ec42b4b454d869714ae761',
 '6c14f768a79e438db324314ad3a595d8',
 '80ecb8ee586840dc987e5e9269bd0cd9',
 '818122fa70724a368f0b83f79f733ca5',
 '4bd72f18db874bc584c8e0d74437b41b',
 '532be3d6f6634a05aef73b27af6f75a5',
 '119f5d115f2d4987a989db783958e3da',
 'b7b789378cc548fa989ac773c81293ac',
 'c5fda3bf4eda488f9a98e2ad266d1e1b',
 '7dda6684f4614330ba4e2b872dc4c419',
 '4c9a98b2bf0b4b45a21660300223a96d',
 'd5ed218bc7f946c8a70b89bd24dfd86e',
 '2bbb4f45893840569a10e8c1567f3925',
 'ad20d7adf65d47c895c9b43af993ec18',
 '8aeeb8a33c534d93880af9e7fcf88342',
 '4ed2b029da7849d7983b07c619a8de86',
 '75b4958d836c4b89943c9aecbebc415b',
 'e6364e495987466885c203798dfdf586',
 '277cecbfca1e4b1d91d5bf6d74cdf0c1',
 'c57f7685eb0f487aa7cca8d24c4e5e05',
 'e415a1232865403ca5c76aa4fd8f15bd',
 'dd0ae5f6384c41d7845f52b9e8bc2950',
 'cf0711c4ac674d4fb2882cba5023cfe7',
 'a945297f856b49bfa0798b16c903b77b',
 'f746fad91a4a426e978fe8f64d343e6a',
 'f8a5dbe1726941afbc360b5009926ac5',
 '697fb0a1e72b4e86bb92d3f70aeb5096',
 '784c909c81364d7aa0525b9bf883b224',
 'd31ed45df899427fb0b0c0d47db9fd83',
 '4f03a297b5c54417a5d99165c497ce83',
 '161cd8cd80ba4093a6ba5cd3fb72ffbe',
 '7ef207ac2579401d98d958a1aa077fd8',
 '7db166cfdea84b2ea8871c9f17643d7a',
 '4a13aa0ae13042a59eb5f45d0a8e6d70',
 'f1217ae275144428adc6dd7a8fc9ea39',
 '2fc8d57847ee4618b45c02dd56d0e419',
 'fb2e4c8ceb0f4767b8c59cff16cb7cbb',
 '17562a9cf6594d7391117767f0060a05',
 '165fb198f42d4ff8a29cfe1554374f6f',
 'a201aae72684474486e95bb703382324',
 '4a32173b4a294f39aad3c17c2f2e0f59',
 '7d8e0346a4a04e84be107745b9a6c038',
 '2b4f9757e8ac4e7aa7da479f01fc372e',
 '421fafa6cca1425eb3c70aa79ae6a535',
 '213f0241db4b4b27be82d7f9b5b79293',
 'bc5e0adc80dd4370acfe571b738ab53d',
 'c4e083b878544dc8854100f4b1e67c9e',
 '2ebde60c422e476190750644da49cd19',
 '1560c7984e6247b9a1fa1e70b64866af',
 '111194bd1bb64592b83be0a278835f89',
 'e6b13ada27f94bb280e5efabc8c57059',
 'f45a59b2b4b54311afd1a52b2bcfcb6c',
 '22330c0555f64c50bcfab05755cd1bbf',
 '0e6c0ca853e94e698f577ce6eceaaffa',
 '8d95116abbac4fa7a00c8fb9243e5960',
 'df6cb05cbebe48d0800a11daad904516',
 '6d234647ff6b42268286fd0bc3b52bfc',
 'a427c4be8dd840b79ca3634566ad0e79']

In [6]:
# Lets create a retriever
retriever = vector_store.as_retriever(search_kwargs={"k": 5})

In [7]:
retriever.invoke("what is the main purpose of the document?")

[Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 21, '_id': '70611eec8f6e4a74817251620284ed19', '_collection_name': 'rag_collection_name'}, page_content='at work appears to be focused on two broad functions: 1) obtaining, documenting, and interpreting\ninformation; and 2) making decisions, giving advice, solving problems, and thinking creatively.\n20'),
 Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 45, '_id': 'c57f7685eb0f487aa7cca8d24c4e5e05', '_collection_name': 'rag_collection_name'}, page_content='If the conversation has multiple distinct capabilities, choose the one that is the\nmost relevant to the **LAST message** in the conversation.\n,→\nExamples:\n**edit_or_critique_provided_text**:\n- "Help me improve my essay, including improving flow and correcting grammar\nerrors."\n,→\n- "Please shorten this paragraph."\n- "Can you proofread my article for grammatical mistakes?"\n- "Here’s my draft speech; can you suggest enhancements?"\n- "Stp aide moi `a corriger ma dissertation."\n**argument_or_summary_generation**:\n- "Make an argument for why the national debt is important."\n- "Write a three-paragraph essay about Abraham Lincoln."\n- "Summarize the Book of Matthew."\n- "Provide a summary of the theory of relativity."'),
 Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 21, '_id': 'aed0e253bbce47c2be92a48c06aa1619', '_collection_name': 'rag_collection_name'}, page_content='all messages.\nFigure 15 presents the distribution of GWAs for the subsample of messages we classify as work-\nrelated.\nAmong work-related messages, the most common GWAs are Documenting/Recording In-\nformation (18.4%), Making Decisions and Solving Problems (14.9%), Thinking Creatively (13.0%),\nWorking with Computers (10.8%), Interpreting the Meaning of Information for Others (10.1%), Get-\nting Information (9.3%), and Providing Consultation and Advice to Others (4.4%). These seven GWAs\ncollectively account for nearly 81% of work-related messages. Overall, the majority of ChatGPT usage\nat work appears to be focused on two broad functions: 1) obtaining, documenting, and interpreting'),
 Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 36, '_id': '435a63791f0a4dc6a5515c9f90593b1d', '_collection_name': 'rag_collection_name'}, page_content='Occupation Group\nDocumenting/\nRecording\nInformation\nMaking\nDecisions\nAnd Solving\nProblems\nThinking\nCreatively\nWorking\nWith\nComputers\nInterpreting\nThe Meaning\nOf\nInformation\nFor Others\nGetting\nInformation\nProviding\nConsultation\nAnd Advice\nTo Others\nManagement\n2\n1\n3\n6\n4\n5\n8\nBusiness\n2\n1\n3\n6\n4\n5\n7\nComputer/Math\n4\n2\n5\n1\n3\n6\n7\nEngineering\n3\n1\n5\n2\n4\n6\n7\nScience\n2\n1\n4\n3\n6\n5\n7\nSocial Service\n2\n1\n3\nX\n5\n4\nX\nLegal\n1\nX\nX\nX\nX\nX\nX\nEducation\n1\n2\n3\n4\n6\n5\n7\nArts/Design/Media\n2\n1\n3\n5\n4\n6\n7\nHealth Professionals\n1\n2\n3\nX\n5\n4\n6\nFood Service\n1\nX\nX\nX\nX\nX\nX\nPersonal Service\n1\n2\n3\nX\n4\n5\nX\nSales\n2\n1\n3\n6\n4\n5\n7\nAdministrative\n2\n1\n3\n7\n4\n5\n8\nTransportation\n2\n1\n3\nX\nX\n4\nX\nMilitary\n2\n1\nX\nX\nX\nX\nX'),
 Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 63, '_id': 'df6cb05cbebe48d0800a11daad904516', '_collection_name': 'rag_collection_name'}, page_content='Occupation Group\nDocumenting/\nRecording\nInformation\nMaking\nDecisions\nAnd Solving\nProblems\nThinking\nCreatively\nWorking\nWith\nComputers\nInterpreting\nThe Meaning\nOf\nInformation\nFor Others\nGetting\nInformation\nProviding\nConsultation\nAnd Advice\nTo Others\nManagement\n3\n2\n4\n7\n5\n1\n6\nBusiness\n3\n2\n6\n7\n4\n1\n5\nComputer/Math\n5\n4\n6\n1\n3\n2\n7\nEngineering\n5\n3\n7\n4\n2\n1\n6\nScience\n2\n3\n6\n7\n4\n1\n5\nSocial Service\n2\n3\n6\nX\n4\n1\n5\nLegal\n2\n3\n6\nX\n4\n1\n5\nEducation\n1\n3\n4\n7\n5\n2\n6\nArts/Design/Media\n2\n3\n4\n7\n5\n1\n6\nHealth Professionals\n2\n5\n6\nX\n4\n1\n3\nHealth Support\n2\n3\n6\nX\n4\n1\n5\nProtective Service\n2\nX\nX\nX\nX\n1\nX\nFood Service\n3\n5\n6\nX\n2\n1\n4\nPersonal Service\n2\n3\n5\nX\n4\n1\n6\nSales\n2\n5\n6\n7\n3\n1\n4\nAdministrative\n2\n4\n6\n8\n3\n1\n5\nConstruction\nX\nX\nX\nX\nX\n1\nX\nInstallation/Repair\nX\nX\nX\nX\nX\n1\nX')]

In [8]:
# produce node for the retrieval
def retrieve(state):
    retrieved_docs = retriever.invoke(state["question"])
    return {"context": retrieved_docs}

In [28]:
from langchain.prompts import ChatPromptTemplate

RAG_PROMPT = """\
    You are a helpful assistant who can answer questions based on the following context only:
    If you cannot answer the question based on the context - you must say "I don't know".
    
    ### Context: 
    {context}
    
    ### Question: 
    {question}
"""

rag_prompt = ChatPromptTemplate.from_template(RAG_PROMPT)

In [29]:
# Create LLM instance
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser

llm = ChatOpenAI(model="gpt-4.1-mini")

In [30]:
# Create a generator
def generate(state):
    docs_content="\n\n".join( doc.page_content for doc in state["context"])
    message = rag_prompt.format_messages(question=state["question"], context=docs_content)
    response = llm.invoke(message)
    return {"response": response.content}

In [14]:
# build a state 
from typing_extensions import TypedDict, List
from langchain_core.documents import Document

class State(TypedDict):
    question: str
    context: List[Document]
    response: str

In [15]:
# Lets build a graph 
from langgraph.graph import START,StateGraph

# 
graph_builder = StateGraph(State).add_sequence([retrieve, generate])
graph_builder.add_edge(START, "retrieve")
graph=graph_builder.compile()

In [31]:
# Run the graph
response = graph.invoke({"question": "how do people use chatgpt?"})

print(response["response"])

People use ChatGPT in various ways that can be broadly classified into three categories according to a taxonomy introduced by the authors: Asking, Doing, and Expressing.

- **Asking:** Users seek information or clarification to inform decisions, corresponding to problem-solving and knowledge work.
- **Doing:** Although not fully detailed in the provided context, this category typically involves users asking ChatGPT to perform tasks or generate specific outputs.
- **Expressing:** This likely involves using ChatGPT for communication, creativity, or sharing ideas, though specific details are not included in the excerpt.

Additionally, ChatGPT usage varies by demographics and purposes:
- It is more frequently used by men, young people, and those with tertiary or graduate education, although the gender gap is narrowing.
- Usage has grown faster in low- and middle-income countries.
- Educated users and those in highly-paid professional occupations are more likely to use ChatGPT for work-related purposes.

Overall, users utilize ChatGPT for obtaining information, problem-solving, work tasks, and potentially creative or expressive activities.

In [18]:
# Lets create some tools 

from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_community.tools.arxiv.tool import ArxivQueryRun

arxiv_tool = ArxivQueryRun()
tavily_tool = TavilySearchResults(max_results=5)

/var/folders/0j/52nrhqqd6hq140jsz5rrd5km0000gq/T/ipykernel_84315/3746444787.py:7: LangChainDeprecationWarning: The class `TavilySearchResults` was deprecated in LangChain 0.3.25 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-tavily package and should be used instead. To use it run `pip install -U :class:`~langchain-tavily` and import as `from :class:`~langchain_tavily import TavilySearch``.
  tavily_tool = TavilySearchResults(max_results=5)

 ## Note

 `ai_rag_tool` returns JSON with BOTH:
- `answer`: The generated response
- `contexts`: List of retrieved document chunks

This allows RAGAS to evaluate whether the answer is grounded in the retrieved contexts.

In [19]:
# lets create a tool for the graph  
from langchain_core.tools import tool
import json

@tool
def ai_rag_tool(question: str):
    """
    Use this tool to answer questions based on the context provided. Input should be a fully formed question.
    """
    
    response = graph.invoke({"question": question})
    
    # Return BOTH the answer AND the retrieved contexts
    # Format: JSON string with answer and contexts
    result = {
        "answer": response["response"],
        "contexts": [doc.page_content for doc in response["context"]]
    }
    
    return json.dumps(result)

In [20]:
# Test the updated ai_rag_tool to verify it returns contexts
test_result = ai_rag_tool.invoke({"question": "How do people use chatgpt?"})
print("Tool result:", test_result[:200], "...")

# Parse it to see the structure
import json
parsed = json.loads(test_result)
print("\nParsed structure:")
print(f"- answer: {parsed['answer'][:100]}...")
print(f"- contexts: {len(parsed['contexts'])} chunks retrieved")
print(f"- First context: {parsed['contexts'][0][:100]}...")

Tool result: {"answer": "People use ChatGPT in various ways, which can be broadly classified into three categories based on the type of output the user is seeking: Asking, Doing, or Expressing. \n\n- **Asking** in ...

Parsed structure:
- answer: People use ChatGPT in various ways, which can be broadly classified into three categories based on t...
- contexts: 5 chunks retrieved
- First context: How People Use ChatGPT
Aaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher ...

In [21]:
# lets create a tool belt

tools = [ai_rag_tool, arxiv_tool, tavily_tool]

In [35]:
# Bind tools to the llm
from langchain_openai import ChatOpenAI

model = ChatOpenAI(model="gpt-4.1",temperature=0)
model=model.bind_tools(tools)

model.invoke("How do people use chatgpt? Use the tools to answer the question")

AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_6kH3UstGZlKey4J6lX71BZxr', 'function': {'arguments': '{"question":"How do people use ChatGPT?"}', 'name': 'ai_rag_tool'}, 'type': 'function'}], 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 22, 'prompt_tokens': 203, 'total_tokens': 225, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4.1-2025-04-14', 'system_fingerprint': 'fp_422e2d36a8', 'id': 'chatcmpl-CSq5SwMExy85AxQ9qQllUAuy1ucSv', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run--a4d88551-220c-4635-a5cd-9b729cdefb14-0', tool_calls=[{'name': 'ai_rag_tool', 'args': {'question': 'How do people use ChatGPT?'}, 'id': 'call_6kH3UstGZlKey4J6lX71BZxr', 'type': 'tool_call'}], usage_metadata={'input_tokens': 203, 'output_tokens': 22, 'total_tokens': 225, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

In [36]:
# Langgraph Agent

from typing import TypedDict, Annotated,List
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    messages:Annotated[list,add_messages]
    context:List[Document]

In [37]:
from langgraph.prebuilt import ToolNode

def call_model(state):
    messages = state["messages"]
    response = model.invoke(messages)
    return {"messages": [response]}

tool_node = ToolNode(tools)

In [38]:
from langgraph.graph import StateGraph,END

uncompiled_graph= StateGraph(AgentState)
uncompiled_graph.add_node("agent",call_model)
uncompiled_graph.add_node("action",tool_node)

In [39]:
# add function/runnable for the conditional edge

def should_continue(state):
    last_message=state["messages"][-1]
    if last_message.tool_calls:
        return "action"
    return END 


uncompiled_graph.set_entry_point("agent")
uncompiled_graph.add_conditional_edges(
    "agent",
    should_continue,
    {
        "action": "action",  # when function returns "action"
        END: END             # when function returns END
    }
)

uncompiled_graph.add_edge("action","agent");

In [40]:
compiled_graph=uncompiled_graph.compile()

In [43]:
# Run the graph
from langchain_core.messages import HumanMessage

inputs={"messages":[HumanMessage(content="How do people use chatgpt? Answer the question using the tools")]}

from langchain_core.messages import ToolMessage, HumanMessage

async for chunk in compiled_graph.astream(inputs, stream_mode="updates"):
    for node, update in chunk.items():
        print(f"\n📡 Receiving updates from node: {node}")

        # Safely handle presence of "messages"
        for msg in update.get("messages", []):
            
            # 🧰 Tool message (result of a tool call)
            if isinstance(msg, ToolMessage):
                print(f"  🧰 ToolMessage from: {msg.name}")
                print(f"  🧾 Content: {msg.content}")
                print(f"  🔖 Tool Call ID: {msg.tool_call_id}")

            # 👤 Human message (user input)
            elif isinstance(msg, HumanMessage):
                print("  👤 HumanMessage:")
                print(f"  💬 {msg.content}")

            # fallback for other message types (AIMessage, etc.)
            else:
                print(f"  ⚙️ Other message type: {type(msg).__name__}")
                print(f"  💬 {getattr(msg, 'content', msg)}")

📡 Receiving updates from node: agent
  ⚙️ Other message type: AIMessage
  💬

📡 Receiving updates from node: action
  🧰 ToolMessage from: ai_rag_tool
  🧾 Content: {"answer": "People use ChatGPT primarily for modifying user text, such as editing, critiquing, and translating, which accounts for about two-thirds of all Writing messages. Around 10% of all messages involve requests for tutoring or teaching, indicating that education is a key use case. A smaller share of messages\u20144.2%\u2014relate to computer programming, and only 1.9% concern companionship or social-emotional issues. Overall, users employ ChatGPT for a variety of purposes categorized as Asking (seeking information or clarification), Doing (modifying or creating content), and Expressing.", "contexts": ["How People Use ChatGPT\nAaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, Carl\nYan Shan, and Kevin Wadman\nNBER Working Paper No. 34255\nSeptember 2025\nJEL No. J01, O3, O4\nABSTRACT\nDespite the rapid adoption of LLM chatbots, little is known about how they are used. We \ndocument the growth of ChatGPT\u2019s consumer product from its launch in November 2022 \nthrough July 2025, when it had been adopted by around 10% of the world\u2019s adult population. \nEarly adopters were disproportionately male but the gender gap has narrowed dramatically, and \nwe find higher growth rates in lower-income countries. Using a privacy-preserving automated", "6\nWho Uses ChatGPT\nIn this section we report basic descriptive facts about who uses consumer ChatGPT. Existing work\ndocuments variation in generative AI use by demographic groups within representative samples in\nthe U.S. (Bick et al. (2024), Hartley et al. (2025)) and within a subset of occupations in Denmark\n(Humlum and Vestergaard, 2025a). All of these papers find that generative AI is used more frequently\nby men, young people, and those with tertiary and/or graduate education.\nWe make three contributions relative to this prior literature. First, we confirm these broad demo-\ngraphic patterns in a global sample rather than a single country. Second, we provide more detail for", "in June 2025. About two-thirds of all Writing messages ask ChatGPT to modify user text (editing,\ncritiquing, translating, etc.) rather than creating new text from scratch. About 10% of all messages\nare requests for tutoring or teaching, suggesting that education is a key use case for ChatGPT.\nTwo of our findings stand in contrast to other work. First, we find the share of messages related\nto computer coding is relatively small: only 4.2% of ChatGPT messages are related to computer\nprogramming, compared to 33% of work-related Claude conversations Handa et al. (2025).8 Second, we\nfind the share of messages related to companionship or social-emotional issues is fairly small: only 1.9%", "have narrowed somewhat in recent months. Third, we find that ChatGPT usage has grown relatively\nfaster in low- and middle-income countries over the last year. Fourth, we find that educated users and\nusers in highly-paid professional occupations are substantially more likely to use ChatGPT for work.\nWe introduce a new taxonomy to classify messages according to the kind of output the user is\nseeking, using a simple rubric that we call Asking, Doing, or Expressing.11\nAsking is when the\nuser is seeking information or clarification to inform a decision, corresponding to problem-solving\nmodels of knowledge work (e.g., Garicano (2000); Garicano and Rossi-Hansberg (2006); Carnehl and", "7\nConclusion\nThis paper studies the rapid growth of ChatGPT, which launched in November 2022. By July 2025,\nChatGPT had been used weekly by more than 700 million users, who were collectively sending more\nthan 2.5 billion messages per day, or about 29,000 messages per second. Yet despite the rapid adop-\ntion of ChatGPT and Generative AI more broadly, little previous evidence existed on how this new\ntechnology is used and who is using it.\nThis is the first economics paper to use internal ChatGPT message data, and we do so while\nintroducing a novel privacy-preserving methodology.\nNo user messages were observed by humans\nduring any part of the work on this paper."]}
  🔖 Tool Call ID: call_5vdXzS0PqYfNWLfxEzQE2JwA

📡 Receiving updates from node: agent
  ⚙️ Other message type: AIMessage
  💬 People use ChatGPT in several main ways:

- Modifying User Text: About two-thirds of all messages involve editing, critiquing, or translating text. This is the most common use.
- Tutoring and Teaching: Around 10% of messages are requests for educational help, making education a key use case.
- Computer Programming: Only about 4.2% of messages relate to coding or programming tasks.
- Companionship or Social-Emotional Support: A small share (1.9%) of messages are about companionship or emotional support.

Overall, users interact with ChatGPT for:
- Asking: Seeking information or clarification.
- Doing: Modifying or creating content.
- Expressing: Sharing thoughts or feelings.

These patterns show that ChatGPT is mainly used for practical writing help, learning, and information-seeking, with less frequent use for coding or emotional support.

# Ragas Baseline And SDG

In [44]:
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings

generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

In [45]:
from ragas.testset import TestsetGenerator

generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)

dataset = generator.generate_with_langchain_docs(docs, testset_size=9)

Applying HeadlinesExtractor:   0%|          | 0/21 [00:00<?, ?it/s]

Applying HeadlineSplitter:   0%|          | 0/64 [00:00<?, ?it/s]

unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node

Applying SummaryExtractor:   0%|          | 0/40 [00:00<?, ?it/s]

Property 'summary' already exists in node 'e4f0a3'. Skipping!
Property 'summary' already exists in node '86c731'. Skipping!
Property 'summary' already exists in node '258a06'. Skipping!
Property 'summary' already exists in node 'd89984'. Skipping!
Property 'summary' already exists in node 'a589a1'. Skipping!
Property 'summary' already exists in node '1b4c61'. Skipping!
Property 'summary' already exists in node 'e3d7e8'. Skipping!
Property 'summary' already exists in node '9fe11a'. Skipping!
Property 'summary' already exists in node '3f798a'. Skipping!
Property 'summary' already exists in node '9aef83'. Skipping!
Property 'summary' already exists in node '20fd16'. Skipping!
Property 'summary' already exists in node '0d9491'. Skipping!
Property 'summary' already exists in node 'e461c1'. Skipping!
Property 'summary' already exists in node '62525d'. Skipping!
Property 'summary' already exists in node '7fd69f'. Skipping!
Property 'summary' already exists in node '5c48ba'. Skipping!
Property 'summary' already exists in node 'f9f5d2'. Skipping!
Property 'summary' already exists in node '09f98c'. Skipping!
Property 'summary' already exists in node 'fa4413'. Skipping!

Applying CustomNodeFilter:   0%|          | 0/4 [00:00<?, ?it/s]

Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/44 [00:00<?, ?it/s]

Property 'summary_embedding' already exists in node 'd89984'. Skipping!
Property 'summary_embedding' already exists in node '86c731'. Skipping!
Property 'summary_embedding' already exists in node '258a06'. Skipping!
Property 'summary_embedding' already exists in node 'e4f0a3'. Skipping!
Property 'summary_embedding' already exists in node 'e3d7e8'. Skipping!
Property 'summary_embedding' already exists in node '9fe11a'. Skipping!
Property 'summary_embedding' already exists in node 'a589a1'. Skipping!
Property 'summary_embedding' already exists in node '3f798a'. Skipping!
Property 'summary_embedding' already exists in node '1b4c61'. Skipping!
Property 'summary_embedding' already exists in node 'fa4413'. Skipping!
Property 'summary_embedding' already exists in node '20fd16'. Skipping!
Property 'summary_embedding' already exists in node '9aef83'. Skipping!
Property 'summary_embedding' already exists in node 'e461c1'. Skipping!
Property 'summary_embedding' already exists in node 'f9f5d2'. Skipping!
Property 'summary_embedding' already exists in node '09f98c'. Skipping!
Property 'summary_embedding' already exists in node '0d9491'. Skipping!
Property 'summary_embedding' already exists in node '62525d'. Skipping!
Property 'summary_embedding' already exists in node '5c48ba'. Skipping!
Property 'summary_embedding' already exists in node '7fd69f'. Skipping!

Applying [CosineSimilarityBuilder, OverlapScoreBuilder]:   0%|          | 0/2 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/10 [00:00<?, ?it/s]

In [46]:
dataset.to_pandas()

,user_input,reference_contexts,reference,synthesizer_name
0,What Acemoglu 2024 say about AI effect on econ...,[Introduction ChatGPT launched in November 202...,Acemoglu (2024) discusses the intensified inte...,single_hop_specifc_query_synthesizer
1,How many 700 million users were sending messag...,[Introduction ChatGPT launched in November 202...,"By July 2025, 700 million users were sending 1...",single_hop_specifc_query_synthesizer
2,how much money us users get from generative ai...,[Conclusion This paper studies the rapid growt...,Collis and Brynjolfsson (2025) estimate that U...,single_hop_specifc_query_synthesizer
3,How has ChatGPT usage changed recently in low-...,[Conclusion This paper studies the rapid growt...,ChatGPT usage has grown especially fast over t...,single_hop_specifc_query_synthesizer
4,How do the ChatGPT adoption and usage statisti...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,ChatGPT launched in November 2022 and by July ...,multi_hop_abstract_query_synthesizer
5,How does the rapid ChatGPT adoption and usage ...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,ChatGPT launched in November 2022 and by July ...,multi_hop_abstract_query_synthesizer
6,how ChatGPT adoption and usage statistics show...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,ChatGPT launched in November 2022 and by July ...,multi_hop_abstract_query_synthesizer
7,How did ChatGPT's user base and message volume...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,"By July 2025, ChatGPT had grown rapidly since ...",multi_hop_specific_query_synthesizer
8,How did the launch of ChatGPT in November 2022...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,ChatGPT launched in November 2022 and experien...,multi_hop_specific_query_synthesizer
9,How did the launch of ChatGPT in November 2022...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,ChatGPT launched in November 2022 and experien...,multi_hop_specific_query_synthesizer

# Code to extract context from the tool calls

In [53]:
import json
import re
from typing import Any, List, Dict, Optional

class ContextParser:
    """Parser to extract contexts from tool call results in agent messages."""
    
    @staticmethod
    def detect_tool_type(message: Any) -> Optional[str]:
        """Detect which tool was called based on the message."""
        try:
            # Check if message has tool_calls attribute
            if hasattr(message, 'tool_calls') and message.tool_calls:
                tool_name = message.tool_calls[0].get('name', '')
                if 'tavily' in tool_name.lower():
                    return 'tavily'
                elif 'arxiv' in tool_name.lower():
                    return 'arxiv'
                elif 'ai_rag' in tool_name.lower() or 'rag' in tool_name.lower():
                    return 'ai_rag'
            
            # Check if it's a ToolMessage with a name attribute
            if hasattr(message, 'name'):
                tool_name = message.name
                if 'tavily' in tool_name.lower():
                    return 'tavily'
                elif 'arxiv' in tool_name.lower():
                    return 'arxiv'
                elif 'ai_rag' in tool_name.lower() or 'rag' in tool_name.lower():
                    return 'ai_rag'
                    
        except Exception as e:
            print(f"Error detecting tool type: {e}")
        return None
    
    @staticmethod
    def extract_content(message: Any) -> Optional[str]:
        """Extract content from a message object."""
        try:
            if hasattr(message, 'content'):
                content = message.content
                if isinstance(content, str):
                    # Handle JSON-like strings with quotes
                    if content.startswith('content="') or content.startswith("content='"):
                        # Find the matching end quote by counting quotes
                        stack = []
                        in_quote = False
                        for i, char in enumerate(content):
                            if char == '"' and (i == 0 or content[i-1] != '\\'):
                                if not in_quote:
                                    stack.append(i)
                                    in_quote = True
                                else:
                                    stack.pop()
                                    if not stack and 'name=' in content[i:]:
                                        return content[8:i]  # 8 is len('content="')
                    return content
        except Exception as e:
            print(f"Error extracting content: {e}")
        return None
    
    @staticmethod
    def parse_tavily_results(content: str) -> List[Dict]:
        """Parse Tavily search results from content string."""
        try:
            # Parse the JSON string
            if isinstance(content, str):
                data = json.loads(content)
                
                # Get results array from the appropriate location
                if isinstance(data, list):
                    results = data
                elif isinstance(data, dict):
                    if 'artifact' in data and 'results' in data['artifact']:
                        results = data['artifact']['results']
                    elif 'results' in data:
                        results = data['results']
                    else:
                        results = []
                else:
                    results = []
                
                # Ensure content is string in each result
                for result in results:
                    if isinstance(result.get('content'), dict):
                        result['content'] = str(result['content'])
                        
                return results
        except Exception as e:
            print(f"Error parsing Tavily results: {str(e)}")
        return []
    
    @staticmethod
    def parse_ai_rag_results(content: str) -> List[Dict]:
        """Parse AI RAG tool results from content string."""
        try:
            # The ai_rag_tool now returns JSON with 'answer' and 'contexts'
            data = json.loads(content)
            
            # Extract contexts list
            if isinstance(data, dict) and 'contexts' in data:
                contexts = data['contexts']
                # Convert to list of dicts with 'content' key for consistency
                documents = [{'content': ctx} for ctx in contexts if ctx]
                return documents
            
            # Fallback: if it's just a plain string (old format)
            elif isinstance(content, str) and content.strip():
                return [{'content': content}]
            
            return []
        except json.JSONDecodeError:
            # If it's not JSON, treat it as plain text
            print("ai_rag content is not JSON, treating as plain text")
            return [{'content': content}] if content else []
        except Exception as e:
            print(f"Error parsing AI RAG results: {str(e)}")
            return []
    
    @staticmethod  
    def parse_arxiv_results(content: str) -> List[Dict]:
        """Parse arXiv results from content string."""
        try:
            papers = []
            # Split by "Published: " but keep the delimiter
            sections = re.split(r'(?=Published: )', content)
            
            for section in sections:
                if not section.strip():
                    continue
                
                # Extract paper details
                date_match = re.search(r'Published: (\d{4}-\d{2}-\d{2})', section)
                title_match = re.search(r'Title: (.*?)(?=\nAuthors:|$)', section, re.DOTALL)
                authors_match = re.search(r'Authors: (.*?)(?=\nSummary:|$)', section, re.DOTALL)
                summary_match = re.search(r'Summary: (.*?)(?=\n\nPublished:|$)', section, re.DOTALL)
                
                if date_match and title_match:
                    summary = summary_match.group(1).strip() if summary_match else ''
                    # Ensure summary is a string
                    if isinstance(summary, dict):
                        summary = str(summary)
                    
                    paper = {
                        'date': date_match.group(1),
                        'title': title_match.group(1).strip(),
                        'authors': authors_match.group(1).strip() if authors_match else '',
                        'summary': summary
                    }
                    papers.append(paper)
            
            return papers
        except Exception as e:
            print(f"Error parsing arXiv results: {str(e)}")
        return []


def parse_tool_call(message: Any) -> List[Dict]:
    """Parse tool call results from a conversation message."""
    parser = ContextParser()
    
    print("\n=== Starting message parsing ===")
    print(f"Message type: {type(message)}")
    
    # Detect tool type
    tool_type = parser.detect_tool_type(message)
    print(f"Detected tool type: {tool_type}")
    
    if tool_type is None:
        print("Could not detect tool type")
        return []
    
    # Extract content
    content = parser.extract_content(message)
    if content is None:
        print("Could not extract content")
        return []
    
    print(f"Extracted content type: {type(content)}")
    
    # Parse based on tool type
    if tool_type == 'tavily':
        results = parser.parse_tavily_results(content)
        print(f"Parsed {len(results)} Tavily results")
        return results
    elif tool_type == 'ai_rag':
        results = parser.parse_ai_rag_results(content)
        print(f"Parsed {len(results)} AI RAG results")
        return results
    elif tool_type == 'arxiv':
        results = parser.parse_arxiv_results(content)
        print(f"Parsed {len(results)} arXiv results")
        return results
    
    return []

In [52]:
def extract_contexts_from_messages(messages: List) -> List[str]:
    """
    Extract all contexts from a list of messages in a conversation.
    This looks for ToolMessage objects and parses their content.
    """
    all_contexts = []
    
    for message in messages:
        # Check if it's a ToolMessage (contains tool call results)
        if hasattr(message, 'name') and hasattr(message, 'content'):
            print(f"\nProcessing ToolMessage from {message.name}")
            
            # Parse the tool call results
            parsed_results = parse_tool_call(message)
            
            # Extract content from parsed results
            for result in parsed_results:
                if isinstance(result, dict):
                    # Different tools return different formats
                    if 'content' in result:
                        all_contexts.append(result['content'])
                    elif 'summary' in result:
                        all_contexts.append(result['summary'])
                    elif 'text' in result:
                        all_contexts.append(result['text'])
    
    return all_contexts


def get_contexts_from_graph_response(response: dict) -> List[str]:
    """
    Extract contexts from a graph response that contains messages.
    """
    if 'messages' not in response:
        print("No messages found in response")
        return []
    
    contexts = extract_contexts_from_messages(response['messages'])
    print(f"\nExtracted {len(contexts)} total contexts")
    return contexts

In [54]:
# Updated evaluation loop with context extraction
for test_row in dataset:
    inputs = {"messages": [HumanMessage(content=test_row.eval_sample.user_input)]}
    response = compiled_graph.invoke(inputs)
    
    # Extract the response text from the last message
    test_row.eval_sample.response = response["messages"][-1].content
    
    # Extract contexts from tool calls in the conversation
    retrieved_contexts = get_contexts_from_graph_response(response)
    
    # Store contexts for evaluation
    test_row.eval_sample.retrieved_contexts = retrieved_contexts
    
    print(f"Question: {test_row.eval_sample.user_input[:100]}...")
    print(f"Retrieved {len(retrieved_contexts)} contexts")
    print("-" * 50)

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: arxiv
Extracted content type: <class 'str'>
Parsed 0 arXiv results

Processing ToolMessage from arxiv

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: arxiv
Extracted content type: <class 'str'>
Parsed 3 arXiv results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 8 total contexts
Question: What Acemoglu 2024 say about AI effect on economy?...
Retrieved 8 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How many 700 million users were sending messages on ChatGPT by July 2025, and what does this indicat...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
ai_rag content is not JSON, treating as plain text
Parsed 0 AI RAG results

Processing ToolMessage from ai_rag_tool

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
Parsed 5 AI RAG results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: how much money us users get from generative ai every year?...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How has ChatGPT usage changed recently in low- and middle-income countries?...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How do the ChatGPT adoption and usage statistics reflect its rapid growth and broad-based impact, es...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How does the rapid ChatGPT adoption and usage statistics, including the growth in message volume and...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: how ChatGPT adoption and usage statistics show ChatGPT growth and adoption from launch to 2025 with ...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How did ChatGPT's user base and message volume evolve by July 2025, and what were the main trends in...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
ai_rag content is not JSON, treating as plain text
Parsed 0 AI RAG results

Processing ToolMessage from ai_rag_tool

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
Parsed 5 AI RAG results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How did the launch of ChatGPT in November 2022 contribute to its rapid global adoption and what key ...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
ai_rag content is not JSON, treating as plain text
Parsed 0 AI RAG results

Processing ToolMessage from ai_rag_tool

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
Parsed 5 AI RAG results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How did the launch of ChatGPT in November 2022 contribute to its unprecedented global diffusion and ...
Retrieved 5 contexts
--------------------------------------------------

In [55]:
# Verify dataset is properly populated
df = dataset.to_pandas()
print("Dataset columns:", df.columns.tolist())
print("\nSample row check:")
sample = df.iloc[0]
print(f"- user_input: {type(sample['user_input'])} - {str(sample['user_input'])[:100]}...")
print(f"- response: {type(sample['response'])} - {str(sample['response'])[:100]}...")
print(f"- reference: {type(sample['reference'])} - {str(sample['reference'])[:100]}...")
print(f"- retrieved_contexts: {type(sample['retrieved_contexts'])} - Length: {len(sample['retrieved_contexts']) if sample['retrieved_contexts'] else 0}")

# Check if all required columns have data
print("\nData completeness check:")
print(f"- Rows with user_input: {df['user_input'].notna().sum()}/{len(df)}")
print(f"- Rows with response: {df['response'].notna().sum()}/{len(df)}")
print(f"- Rows with reference: {df['reference'].notna().sum()}/{len(df)}")
print(f"- Rows with retrieved_contexts: {df['retrieved_contexts'].notna().sum()}/{len(df)}")

Dataset columns: ['user_input', 'retrieved_contexts', 'reference_contexts', 'response', 'reference', 'synthesizer_name']

Sample row check:
- user_input: <class 'str'> - What Acemoglu 2024 say about AI effect on economy?...
- response: <class 'str'> - Daron Acemoglu’s 2024 work on the economic effects of AI, especially as summarized in his paper “The...
- reference: <class 'str'> - Acemoglu (2024) discusses the intensified interest in the effects of artificial intelligence on econ...
- retrieved_contexts: <class 'list'> - Length: 8

Data completeness check:
- Rows with user_input: 10/10
- Rows with response: 10/10
- Rows with reference: 10/10
- Rows with retrieved_contexts: 10/10

In [56]:
# Run RAGAS evaluation with properly populated dataset
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy, ContextEntityRecall, NoiseSensitivity
from ragas import evaluate, RunConfig
from ragas import EvaluationDataset
from ragas.llms import LangchainLLMWrapper

# Create evaluation dataset from pandas
evaluation_dataset = EvaluationDataset.from_pandas(dataset.to_pandas())

# Configure evaluation
custom_run_config = RunConfig(timeout=360)
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))

# Run evaluation with all metrics
baseline_result = evaluate(
    dataset=evaluation_dataset,
    metrics=[
        LLMContextRecall(),      # Requires: user_input, retrieved_contexts, reference
        Faithfulness(),          # Requires: user_input, response, retrieved_contexts
        FactualCorrectness(),    # Requires: user_input, response, reference
        ResponseRelevancy(),     # Requires: user_input, response
        ContextEntityRecall(),   # Requires: user_input, retrieved_contexts, reference
        NoiseSensitivity()       # Requires: user_input, retrieved_contexts
    ],
    llm=evaluator_llm,
    run_config=custom_run_config
)

# Display results
print("RAGAS Evaluation Results:")
print(baseline_result)

Evaluating:   0%|          | 0/60 [00:00<?, ?it/s]

Exception raised in Job[35]: TimeoutError()

RAGAS Evaluation Results:
{'context_recall': 0.5893, 'faithfulness': 0.9107, 'factual_correctness': 0.4860, 'answer_relevancy': 0.9497, 'context_entity_recall': 0.3454, 'noise_sensitivity_relevant': 0.3869}

In [58]:
baseline_result.to_pandas()

,user_input,retrieved_contexts,reference_contexts,response,reference,context_recall,faithfulness,factual_correctness,answer_relevancy,context_entity_recall,noise_sensitivity_relevant
0,What Acemoglu 2024 say about AI effect on econ...,[Acemoglu and Johnson (2007) put forward the u...,[Introduction ChatGPT launched in November 202...,Daron Acemoglu’s 2024 work on the economic eff...,Acemoglu (2024) discusses the intensified inte...,1.000000,1.000000,0.06,0.941399,0.250000,0.035714
1,How many 700 million users were sending messag...,"[According to Brad Lightcap, OpenAI's Chief Op...",[Introduction ChatGPT launched in November 202...,"By July 2025, ChatGPT had over 700 million wee...","By July 2025, 700 million users were sending 1...",0.500000,1.000000,0.57,0.929332,0.600000,0.125000
2,how much money us users get from generative ai...,[educated and working in professional occupati...,[Conclusion This paper studies the rapid growt...,US users derive a surplus value of at least $9...,Collis and Brynjolfsson (2025) estimate that U...,1.000000,1.000000,0.75,0.920548,0.625000,0.400000
3,How has ChatGPT usage changed recently in low-...,"[But as of mid-2025, that gender gap was found...",[Conclusion This paper studies the rapid growt...,Recent studies and reports indicate that ChatG...,ChatGPT usage has grown especially fast over t...,1.000000,0.916667,0.47,0.986357,0.500000,0.583333
4,How do the ChatGPT adoption and usage statisti...,[### 5. How fast is ChatGPT growing in mobile ...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,ChatGPT’s adoption and usage statistics highli...,ChatGPT launched in November 2022 and by July ...,0.142857,1.000000,0.39,0.933945,0.071429,0.553191
5,How does the rapid ChatGPT adoption and usage ...,[ChatGPT launched as a “research preview” in l...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,"By July 2025, ChatGPT's adoption and usage sta...",ChatGPT launched in November 2022 and by July ...,0.714286,0.918033,0.53,0.939868,0.375000,NaN
6,how ChatGPT adoption and usage statistics show...,[Image 8: Profile picture of Nerdynav By Nerdy...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,Here’s a summary of ChatGPT’s adoption and usa...,ChatGPT launched in November 2022 and by July ...,0.250000,1.000000,0.40,0.957209,0.222222,0.719298
7,How did ChatGPT's user base and message volume...,[So the paper provides analysis of the chatbot...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,"By July 2025, ChatGPT's user base and message ...","By July 2025, ChatGPT had grown rapidly since ...",0.285714,0.800000,0.49,0.988272,0.400000,0.480000
8,How did the launch of ChatGPT in November 2022...,[7\nConclusion\nThis paper studies the rapid g...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,The launch of ChatGPT in November 2022 contrib...,ChatGPT launched in November 2022 and experien...,0.666667,1.000000,0.56,0.963721,0.210526,0.391304
9,How did the launch of ChatGPT in November 2022...,[7\nConclusion\nThis paper studies the rapid g...,[<1-hop>\n\nIntroduction ChatGPT launched in N...,The launch of ChatGPT in November 2022 was piv...,ChatGPT launched in November 2022 and experien...,0.333333,0.472222,0.64,0.936727,0.200000,0.194444

In [59]:
print(baseline_result)

{'context_recall': 0.5893, 'faithfulness': 0.9107, 'factual_correctness': 0.4860, 'answer_relevancy': 0.9497, 'context_entity_recall': 0.3454, 'noise_sensitivity_relevant': 0.3869}

## Let us use Cohere's Rerank model for re-Evaluating

Now that we've got our baseline - let's make a change and see how the model improves or doesn't improve!

In [68]:
# Let us build the adjusted retriever using cohere's rerank model

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance,VectorParams
from langchain_openai import OpenAIEmbeddings

text_splitter = RecursiveCharacterTextSplitter(chunk_size=750, chunk_overlap=100)
split_docs = text_splitter.split_documents(docs)
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

client = QdrantClient(":memory:")
client.create_collection(
    collection_name="cohere_rag_collection",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

vector_store = QdrantVectorStore(
    client=client,
    collection_name="cohere_rag_collection",
    embedding=embeddings,
)
vector_store.add_documents(documents=split_docs)
cohere_retriever = vector_store.as_retriever(search_kwargs={"k": 20})


from langchain.retrievers.contextual_compression import ContextualCompressionRetriever
from langchain_cohere import CohereRerank

def cohere_adjusted_retriever(state):
  compressor = CohereRerank(model="rerank-v3.5",top_n=10)
  compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=cohere_retriever
  )
  retrieved_docs = compression_retriever.invoke(state["question"])
  return {"context" : retrieved_docs}



# Lets build a graph 
from langgraph.graph import START,StateGraph

# 
cohere_graph_builder = StateGraph(State).add_sequence([cohere_adjusted_retriever, generate])
cohere_graph_builder.add_edge(START, "cohere_adjusted_retriever")
cohere_graph=cohere_graph_builder.compile()

# lets create a tool for the graph  
from langchain_core.tools import tool
import json

@tool
def ai_rag_tool_cohere(question: str):
    """
    Use this tool to answer questions based on the context provided. Input should be a fully formed question.
    """
    
    response = cohere_graph.invoke({"question": question})
    
    # Return BOTH the answer AND the retrieved contexts
    # Format: JSON string with answer and contexts
    result = {
        "answer": response["response"],
        "contexts": [doc.page_content for doc in response["context"]]
    }
    
    return json.dumps(result)

tools_cohere = [ai_rag_tool_cohere, arxiv_tool, tavily_tool]

# Bind tools to the llm
from langchain_openai import ChatOpenAI

model = ChatOpenAI(model="gpt-4.1",temperature=0)
model=model.bind_tools(tools_cohere)


from langgraph.prebuilt import ToolNode

def call_model(state):
    messages = state["messages"]
    response = model.invoke(messages)
    return {"messages": [response]}

tool_node_cohere = ToolNode(tools_cohere)

from langgraph.graph import StateGraph,END

cohere_uncompiled_graph= StateGraph(AgentState)
cohere_uncompiled_graph.add_node("agent",call_model)
cohere_uncompiled_graph.add_node("action",tool_node_cohere)

def should_continue(state):
    last_message=state["messages"][-1]
    if last_message.tool_calls:
        return "action"
    return END 


cohere_uncompiled_graph.set_entry_point("agent")
cohere_uncompiled_graph.add_conditional_edges(
    "agent", should_continue
)
cohere_uncompiled_graph.add_edge("action","agent");

cohere_compiled_graph=cohere_uncompiled_graph.compile()

# Run the graph
from langchain_core.messages import HumanMessage

inputs={"messages":[HumanMessage(content="How do people use chatgpt? Answer the question using the tools")]}

async for chunk in cohere_compiled_graph.astream(inputs,stream_mode="updates"):
    for node,values in chunk.items():
        print("Receiving updates from node",node)
        print(values["messages"])
        print("\n\n")

Receiving updates from node agent
[AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_rvxQpTxnLMvgYWt04v2gB12H', 'function': {'arguments': '{"question":"How do people use ChatGPT?"}', 'name': 'ai_rag_tool_cohere'}, 'type': 'function'}], 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 24, 'prompt_tokens': 204, 'total_tokens': 228, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4.1-2025-04-14', 'system_fingerprint': 'fp_422e2d36a8', 'id': 'chatcmpl-CSrIjd5t5SZ57iEnBdVjwmTYsh7co', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run--ddd6a0eb-43d4-4e7b-80a8-643f96494cbc-0', tool_calls=[{'name': 'ai_rag_tool_cohere', 'args': {'question': 'How do people use ChatGPT?'}, 'id': 'call_rvxQpTxnLMvgYWt04v2gB12H', 'type': 'tool_call'}], usage_metadata={'input_tokens': 204, 'output_tokens': 24, 'total_tokens': 228, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]



Receiving updates from node action
[ToolMessage(content='{"answer": "People use ChatGPT for a variety of purposes, with major uses including Practical Guidance, Writing, and Seeking Information, which together account for nearly 78% of all messages. Writing is particularly common in work-related use, making up 42% of work-related messages. Most writing requests involve modifying user inputs (such as editing, critiquing, or translating) rather than creating new text from scratch. Education is a key use case, with 10.2% of all user messages and 36% of Practical Guidance messages being requests for tutoring or teaching. General how-to advice constitutes 8.5% of messages and 30% of Practical Guidance. Technical help messages include computer programming (4.2%), mathematical calculations (3%), and data analysis (0.4%). Messages related to companionship or social-emotional issues are relatively small, with only 1.9% about relationships and personal reflection. Overall, about 70% of ChatGPT queries are non-work-related, and non-work usage is increasing faster than work-related usage. Users tend to use ChatGPT as an advisor or research assistant, seeking information or clarification (Asking), having ChatGPT perform tasks (Doing), or expressing ideas (Expressing).", "contexts": ["How People Use ChatGPT\\nAaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, Carl\\nYan Shan, and Kevin Wadman\\nNBER Working Paper No. 34255\\nSeptember 2025\\nJEL No. J01, O3, O4\\nABSTRACT\\nDespite the rapid adoption of LLM chatbots, little is known about how they are used. We \\ndocument the growth of ChatGPT\\u2019s consumer product from its launch in November 2022 \\nthrough July 2025, when it had been adopted by around 10% of the world\\u2019s adult population. \\nEarly adopters were disproportionately male but the gender gap has narrowed dramatically, and \\nwe find higher growth rates in lower-income countries. Using a privacy-preserving automated", "educated and working in professional occupations are more likely to use ChatGPT for work-related\\nmessages and for Asking rather than Doing messages at work.\\nOverall, our findings suggest that ChatGPT has a broad-based impact on the global economy.\\nThe fact that non-work usage is increasing faster suggests that the welfare gains from generative AI\\nusage could be substantial. Collis and Brynjolfsson (2025) estimate that US users would have to\\nbe paid $98 to forgo using generative AI for a month, implying a surplus of at least $97 billion a\\nyear. Within work usage, we find that users currently appear to derive value from using ChatGPT\\nas an advisor or research assistant, not just a technology that performs job tasks directly.\\nStill,", "earlier sign-ups have consistently had higher usage, but that usage has also consistently grown within\\nevery cohort, which we interpret as due to both (1) improvements in the capabilities of the models,\\nand (2) users slowly discovering new uses for existing capabilities.\\n5\\nHow ChatGPT is Used\\nWe next report on the content of ChatGPT conversations using a variety of different taxonomies. For\\neach taxonomy we describe a \\u201cprompt\\u201d which defines a set of categories, and then apply an LLM\\nto map each message to a category. Our categories often apply to the user\\u2019s intention, rather than\\nthe text of the conversation, and as such we never directly observe the ground truth. Nevertheless", "suggests that most user Writing conversations with ChatGPT are requests to modify user inputs\\nrather than to create something new. Education is a major use case for ChatGPT. 10.2% of all user\\nmessages and 36% of Practical Guidance messages are requests for Tutoring or Teaching. Another\\nlarge share - 8.5% in total and 30% of Practical Guidance - is general how-to advice on a variety\\nof topics. Technical Help includes Computer Programming (4.2% of messages), Mathematical Calcu-\\nlations (3%), and Data Analysis (0.4%). Looking at the topic of Self-Expression, only 2.4% of all\\nChatGPT messages are about Relationships and Personal Reflection (1.9%) or Games and Role Play\\n(0.4%).", "7\\nConclusion\\nThis paper studies the rapid growth of ChatGPT, which launched in November 2022. By July 2025,\\nChatGPT had been used weekly by more than 700 million users, who were collectively sending more\\nthan 2.5 billion messages per day, or about 29,000 messages per second. Yet despite the rapid adop-\\ntion of ChatGPT and Generative AI more broadly, little previous evidence existed on how this new\\ntechnology is used and who is using it.\\nThis is the first economics paper to use internal ChatGPT message data, and we do so while\\nintroducing a novel privacy-preserving methodology.\\nNo user messages were observed by humans\\nduring any part of the work on this paper.", "have narrowed somewhat in recent months. Third, we find that ChatGPT usage has grown relatively\\nfaster in low- and middle-income countries over the last year. Fourth, we find that educated users and\\nusers in highly-paid professional occupations are substantially more likely to use ChatGPT for work.\\nWe introduce a new taxonomy to classify messages according to the kind of output the user is\\nseeking, using a simple rubric that we call Asking, Doing, or Expressing.11\\nAsking is when the\\nuser is seeking information or clarification to inform a decision, corresponding to problem-solving\\nmodels of knowledge work (e.g., Garicano (2000); Garicano and Rossi-Hansberg (2006); Carnehl and", "6\\nWho Uses ChatGPT\\nIn this section we report basic descriptive facts about who uses consumer ChatGPT. Existing work\\ndocuments variation in generative AI use by demographic groups within representative samples in\\nthe U.S. (Bick et al. (2024), Hartley et al. (2025)) and within a subset of occupations in Denmark\\n(Humlum and Vestergaard, 2025a). All of these papers find that generative AI is used more frequently\\nby men, young people, and those with tertiary and/or graduate education.\\nWe make three contributions relative to this prior literature. First, we confirm these broad demo-\\ngraphic patterns in a global sample rather than a single country. Second, we provide more detail for", "1\\nIntroduction\\nChatGPT launched in November 2022. By July 2025, 18 billion messages were being sent each week\\nby 700 million users, representing around 10% of the global adult population.1 For a new technology,\\nthis speed of global diffusion has no precedent (Bick et al., 2024).\\nThis paper studies consumer usage of ChatGPT, the first mass-market chatbot and likely the\\nlargest.2 ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence (AI)\\ndeveloped over the last decade and generally considered to represent an acceleration in AI capabilities.3\\nThe sudden growth in LLM abilities and adoption has intensified interest in the effects of artificial", "in June 2025. About two-thirds of all Writing messages ask ChatGPT to modify user text (editing,\\ncritiquing, translating, etc.) rather than creating new text from scratch. About 10% of all messages\\nare requests for tutoring or teaching, suggesting that education is a key use case for ChatGPT.\\nTwo of our findings stand in contrast to other work. First, we find the share of messages related\\nto computer coding is relatively small: only 4.2% of ChatGPT messages are related to computer\\nprogramming, compared to 33% of work-related Claude conversations Handa et al. (2025).8 Second, we\\nfind the share of messages related to companionship or social-emotional issues is fairly small: only 1.9%", "No user messages were observed by humans\\nduring any part of the work on this paper.\\nThis paper documents eight important facts about ChatGPT. First, as of July 2025 about 70%\\nof ChatGPT consumer queries were unrelated to work; while both work-related and non-work-related\\nqueries have been increasing, non-work queries have been increasing faster.\\nSecond, the three most common ChatGPT conversation topics are Practical Guidance, Writing,\\nand Seeking Information, collectively accounting for nearly 78% of all messages.\\nComputer Pro-\\ngramming and Relationships and Personal Reflection account for only 4.2% and 1.9% of messages\\nrespectively.\\nThird, Writing is by far the most common work use, accounting for 42% of work-related messages"]}', name='ai_rag_tool_cohere', id='e9555152-8500-49eb-a90c-9195ac580f50', tool_call_id='call_rvxQpTxnLMvgYWt04v2gB12H')]



Receiving updates from node agent
[AIMessage(content='People use ChatGPT for a wide range of purposes, with the most common uses being:\n\n1. Practical Guidance: Many users seek advice on how to do things, including general how-to advice and technical help (like programming, math, or data analysis). About 8.5% of all messages are general how-to questions, and technical help (programming, math, data analysis) makes up a smaller but significant portion.\n\n2. Writing: A large share of users ask ChatGPT to help with writing tasks. This includes editing, critiquing, or translating text, rather than just creating new content from scratch. Writing is especially common for work-related use, making up 42% of work-related messages.\n\n3. Seeking Information: Users often use ChatGPT as an advisor or research assistant, asking for information or clarification to inform decisions.\n\n4. Education: About 10% of all messages are requests for tutoring or teaching, making education a key use case.\n\n5. Self-Expression and Companionship: A smaller portion of messages (about 2%) are about relationships, personal reflection, or seeking companionship.\n\nOverall, about 70% of ChatGPT queries are non-work-related, and non-work usage is growing faster than work-related usage. Users tend to use ChatGPT for Asking (seeking information), Doing (having tasks performed), or Expressing (sharing ideas or feelings). The most common topics are practical guidance, writing, and seeking information, which together account for nearly 78% of all messages.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 308, 'prompt_tokens': 2096, 'total_tokens': 2404, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4.1-2025-04-14', 'system_fingerprint': 'fp_422e2d36a8', 'id': 'chatcmpl-CSrIoFvC8BXfSFT4EauSnlfQtGAZ9', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='run--82a0210d-fa83-41f7-84b3-8eb0dcff0dfa-0', usage_metadata={'input_tokens': 2096, 'output_tokens': 308, 'total_tokens': 2404, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]

In [69]:
import time
import copy

rerank_dataset = copy.deepcopy(dataset)

# Updated evaluation loop with context extraction
for test_row in rerank_dataset:
    inputs = {"messages": [HumanMessage(content=test_row.eval_sample.user_input)]}
    response = cohere_compiled_graph.invoke(inputs)
    
    # DEBUG: Print which tools were called
    print(f"\n=== Question: {test_row.eval_sample.user_input[:80]}... ===")
    for msg in response["messages"]:
        if hasattr(msg, 'tool_calls') and msg.tool_calls:
            for tool_call in msg.tool_calls:
                print(f"Tool called: {tool_call.get('name', 'unknown')}")
        if hasattr(msg, 'name') and msg.name:
            print(f"Tool response from: {msg.name}")
    
    # Extract the response text from the last message
    test_row.eval_sample.response = response["messages"][-1].content
    
    # Extract contexts from tool calls in the conversation
    retrieved_contexts = get_contexts_from_graph_response(response)
    
    # Store contexts for evaluation
    test_row.eval_sample.retrieved_contexts = retrieved_contexts
    
    print(f"Retrieved {len(retrieved_contexts)} contexts")
    print("-" * 50)
    time.sleep(2)

=== Question: What Acemoglu 2024 say about AI effect on economy?... ===
Tool called: arxiv
Tool response from: arxiv
Tool called: tavily_search_results_json
Tool response from: tavily_search_results_json

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: arxiv
Extracted content type: <class 'str'>
Parsed 0 arXiv results

Processing ToolMessage from arxiv

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: arxiv
Extracted content type: <class 'str'>
Parsed 3 arXiv results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 8 total contexts
Retrieved 8 contexts
--------------------------------------------------

=== Question: How many 700 million users were sending messages on ChatGPT by July 2025, and wh... ===
Tool called: tavily_search_results_json
Tool response from: tavily_search_results_json

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Retrieved 5 contexts
--------------------------------------------------

=== Question: how much money us users get from generative ai every year?... ===
Tool called: ai_rag_tool_cohere
Tool response from: ai_rag_tool_cohere

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
ai_rag content is not JSON, treating as plain text
Parsed 0 AI RAG results

Processing ToolMessage from ai_rag_tool_cohere

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
Parsed 10 AI RAG results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 10 total contexts
Retrieved 10 contexts
--------------------------------------------------

=== Question: How has ChatGPT usage changed recently in low- and middle-income countries?... ===
Tool called: tavily_search_results_json
Tool response from: tavily_search_results_json

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Retrieved 5 contexts
--------------------------------------------------

=== Question: How do the ChatGPT adoption and usage statistics reflect its rapid growth and br... ===
Tool called: tavily_search_results_json
Tool response from: tavily_search_results_json

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Retrieved 5 contexts
--------------------------------------------------

=== Question: How does the rapid ChatGPT adoption and usage statistics, including the growth i... ===
Tool called: tavily_search_results_json
Tool response from: tavily_search_results_json

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Retrieved 5 contexts
--------------------------------------------------

=== Question: how ChatGPT adoption and usage statistics show ChatGPT growth and adoption from ... ===
Tool called: tavily_search_results_json
Tool response from: tavily_search_results_json

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Retrieved 5 contexts
--------------------------------------------------

=== Question: How did ChatGPT's user base and message volume evolve by July 2025, and what wer... ===
Tool called: tavily_search_results_json
Tool response from: tavily_search_results_json

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Retrieved 5 contexts
--------------------------------------------------

=== Question: How did the launch of ChatGPT in November 2022 contribute to its rapid global ad... ===
Tool called: tavily_search_results_json
Tool response from: tavily_search_results_json

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Retrieved 5 contexts
--------------------------------------------------

=== Question: How did the launch of ChatGPT in November 2022 contribute to its unprecedented g... ===
Tool called: ai_rag_tool_cohere
Tool response from: ai_rag_tool_cohere

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
ai_rag content is not JSON, treating as plain text
Parsed 0 AI RAG results

Processing ToolMessage from ai_rag_tool_cohere

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: ai_rag
Extracted content type: <class 'str'>
Parsed 10 AI RAG results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 10 total contexts
Retrieved 10 contexts
--------------------------------------------------

In [71]:
# Verify dataset is properly populated
df = rerank_dataset.to_pandas()
print("Dataset columns:", df.columns.tolist())
print("\nSample row check:")
sample = df.iloc[0]
print(f"- user_input: {type(sample['user_input'])} - {str(sample['user_input'])[:100]}...")
print(f"- response: {type(sample['response'])} - {str(sample['response'])[:100]}...")
print(f"- reference: {type(sample['reference'])} - {str(sample['reference'])[:100]}...")
print(f"- retrieved_contexts: {type(sample['retrieved_contexts'])} - Length: {len(sample['retrieved_contexts']) if sample['retrieved_contexts'] else 0}")

# Check if all required columns have data
print("\nData completeness check:")
print(f"- Rows with user_input: {df['user_input'].notna().sum()}/{len(df)}")
print(f"- Rows with response: {df['response'].notna().sum()}/{len(df)}")
print(f"- Rows with reference: {df['reference'].notna().sum()}/{len(df)}")
print(f"- Rows with retrieved_contexts: {df['retrieved_contexts'].notna().sum()}/{len(df)}")

Dataset columns: ['user_input', 'retrieved_contexts', 'reference_contexts', 'response', 'reference', 'synthesizer_name']

Sample row check:
- user_input: <class 'str'> - What Acemoglu 2024 say about AI effect on economy?...
- response: <class 'str'> - Daron Acemoglu's 2024 work on the economic effects of AI, especially as summarized in his paper "The...
- reference: <class 'str'> - Acemoglu (2024) discusses the intensified interest in the effects of artificial intelligence on econ...
- retrieved_contexts: <class 'list'> - Length: 8

Data completeness check:
- Rows with user_input: 10/10
- Rows with response: 10/10
- Rows with reference: 10/10
- Rows with retrieved_contexts: 10/10

In [72]:
# Run RAGAS evaluation with properly populated dataset
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy, ContextEntityRecall, NoiseSensitivity
from ragas import evaluate, RunConfig
from ragas import EvaluationDataset
from ragas.llms import LangchainLLMWrapper

# Create evaluation dataset from pandas
cohere_evaluation_dataset = EvaluationDataset.from_pandas(rerank_dataset.to_pandas())

# Configure evaluation
custom_run_config = RunConfig(timeout=360)
cohere_evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))

# Run evaluation with all metrics
cohere_rerank_result = evaluate(
    dataset=cohere_evaluation_dataset,
    metrics=[
        LLMContextRecall(),      # Requires: user_input, retrieved_contexts, reference
        Faithfulness(),          # Requires: user_input, response, retrieved_contexts
        FactualCorrectness(),    # Requires: user_input, response, reference
        ResponseRelevancy(),     # Requires: user_input, response
        ContextEntityRecall(),   # Requires: user_input, retrieved_contexts, reference
        NoiseSensitivity()       # Requires: user_input, retrieved_contexts
    ],
    llm=cohere_evaluator_llm,
    run_config=custom_run_config
)

# Display results
print("RAGAS Evaluation Results:")
print(cohere_rerank_result)

Evaluating:   0%|          | 0/60 [00:00<?, ?it/s]

Exception raised in Job[39]: InternalServerError(<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>api.openai.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              <span class="inline-block">Web server is returning an unknown error</span>
              <span class="code-label">Error code 520</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2025-10-20 21:07:27 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">

<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Salt Lake City</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">api.openai.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-5xx-errors/error-520/">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">991b7c11fb257b25</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">73.228.81.4</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.openai.com" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>)
Exception raised in Job[29]: TimeoutError()
Exception raised in Job[35]: TimeoutError()
Exception raised in Job[59]: TimeoutError()

RAGAS Evaluation Results:
{'context_recall': 0.7298, 'faithfulness': 0.9502, 'factual_correctness': 0.5200, 'answer_relevancy': 0.9410, 'context_entity_recall': 0.2951, 'noise_sensitivity_relevant': 0.4080}

In [73]:
print(cohere_rerank_result)

{'context_recall': 0.7298, 'faithfulness': 0.9502, 'factual_correctness': 0.5200, 'answer_relevancy': 0.9410, 'context_entity_recall': 0.2951, 'noise_sensitivity_relevant': 0.4080}

In [67]:
print(baseline_result)

{'context_recall': 0.5893, 'faithfulness': 0.9107, 'factual_correctness': 0.4860, 'answer_relevancy': 0.9497, 'context_entity_recall': 0.3454, 'noise_sensitivity_relevant': 0.3869}