# Load the pdf files and split them into chunks

In [1]:
from langchain_community.document_loaders import DirectoryLoader
from langchain_community.document_loaders import PyMuPDFLoader

directory_loader = DirectoryLoader("data", glob="**/*.pdf", loader_cls=PyMuPDFLoader)

docs = directory_loader.load()

print(docs)

[Document(metadata={'producer': '', 'creator': 'Microsoft Word', 'creationdate': '2025-10-17T19:51:23+00:00', 'source': 'data/rag-test.pdf', 'file_path': 'data/rag-test.pdf', 'total_pages': 1, 'format': 'PDF 1.7', 'title': '', 'author': 'Amit Shrigondekar', 'subject': '', 'keywords': '', 'moddate': '2025-10-17T19:51:23+00:00', 'trapped': '', 'modDate': "D:20251017195123+00'00'", 'creationDate': "D:20251017195123+00'00'", 'page': 0}, page_content='This is a text to prove that RAG works.  \nAmit Shrigondekar is the full stack engineer. His skills are backend specifically in node, \njava, bash , Kubernetes etc. \nAmit likes to spend time building things that automates boring repetitive error-prone \ntedious work so that it can be done efficiently. \nAmit does not like to be told details on how he need to perform his role at work. Amit likes \nto explore, design, research himself to figure out the right way to architect and build things.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 0}, page_content='NBER WORKING PAPER SERIES\nHOW PEOPLE USE CHATGPT\nAaron Chatterji\nThomas Cunningham\nDavid J. Deming\nZoe Hitzig\nChristopher Ong\nCarl Yan Shan\nKevin Wadman\nWorking Paper 34255\nhttp://www.nber.org/papers/w34255\nNATIONAL BUREAU OF ECONOMIC RESEARCH\n1050 Massachusetts Avenue\nCambridge, MA 02138\nSeptember 2025\nWe acknowledge help and comments from Joshua Achiam, Hemanth Asirvatham, Ryan \nBeiermeister, Rachel Brown, Cassandra Duchan Solis, Jason Kwon, Elliott Mokski, Kevin Rao, \nHarrison Satcher, Gawesha Weeratunga, Hannah Wong, and Analytics & Insights team. We \nespecially thank Tyna Eloundou and Pamela Mishkin who in several ways laid the foundation for \nthis work. This study was approved by Harvard IRB (IRB25-0983). A repository containing all \ncode run to produce the analyses in this paper is available on request. The views expressed herein \nare those of the authors and do not necessarily reflect the views of the National Bureau of \nEconomic Research.\nAt least one co-author has disclosed additional relationships of potential relevance for this research. \nFurther information is available online at http://www.nber.org/papers/w34255\nNBER working papers are circulated for discussion and comment purposes. They have not been \npeer-reviewed or been subject to the review by the NBER Board of Directors that accompanies \nofficial NBER publications.\n© 2025 by Aaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, \nCarl Yan Shan, and Kevin Wadman. All rights reserved. Short sections of text, not to exceed two \nparagraphs, may be quoted without explicit permission provided that full credit, including © \nnotice, is given to the source.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='How People Use ChatGPT\nAaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, Carl\nYan Shan, and Kevin Wadman\nNBER Working Paper No. 34255\nSeptember 2025\nJEL No. J01, O3, O4\nABSTRACT\nDespite the rapid adoption of LLM chatbots, little is known about how they are used. We \ndocument the growth of ChatGPT’s consumer product from its launch in November 2022 \nthrough July 2025, when it had been adopted by around 10% of the world’s adult population. \nEarly adopters were disproportionately male but the gender gap has narrowed dramatically, and \nwe find higher growth rates in lower-income countries. Using a privacy-preserving automated \npipeline, we classify usage patterns within a representative sample of ChatGPT conversations. \nWe find steady growth in work-related messages but even faster growth in non-work-related \nmessages, which have grown from 53% to more than 70% of all usage. Work usage is more \ncommon for educated users in highly-paid professional occupations. We classify messages by \nconversation topic and find that “Practical Guidance,” “Seeking Information,” and “Writing” are \nthe three most common topics and collectively account for nearly 80% of all conversations. \nWriting dominates work-related tasks, highlighting chatbots’ unique ability to generate digital \noutputs compared to traditional search engines. Computer programming and self-expression both \nrepresent relatively small shares of use. Overall, we find that ChatGPT provides economic value \nthrough decision support, which is especially important in knowledge-intensive jobs.\nAaron Chatterji\nDuke University\nFuqua School of Business \nand OpenAI\nronnie@duke.edu\nThomas Cunningham \nOpenAI\ntom.cunningham@gmail.com\nDavid J. Deming\nHarvard University\nHarvard Kennedy School \nand NBER\ndavid_deming@harvard.edu\nZoe Hitzig\nOpenAI\nand Harvard Society of Fellows\nzhitzig@g.harvard.edu\nChristopher Ong\nHarvard University\nand OpenAI\nchristopherong@hks.harvard.edu\nCarl Yan Shan\nOpenAI\ncshan@openai.com\nKevin Wadman\nOpenAI\nkevin.wadman@c-openai.com'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='1\nIntroduction\nChatGPT launched in November 2022. By July 2025, 18 billion messages were being sent each week\nby 700 million users, representing around 10% of the global adult population.1 For a new technology,\nthis speed of global diffusion has no precedent (Bick et al., 2024).\nThis paper studies consumer usage of ChatGPT, the first mass-market chatbot and likely the\nlargest.2 ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence (AI)\ndeveloped over the last decade and generally considered to represent an acceleration in AI capabilities.3\nThe sudden growth in LLM abilities and adoption has intensified interest in the effects of artificial\nintelligence on economic growth (Acemoglu, 2024; Korinek and Suh, 2024); employment (Eloundou\net al., 2025); and society (Kulveit et al., 2025). However, despite the rapid adoption of LLMs, there\nis limited public information on how they are used. A number of surveys have measured self-reported\nadoption of LLMs (Bick et al., 2024; Pew Research Center, 2025); however there are reasons to expect\nbias in self-reports (Ling and Imas, 2025), and none of these papers have been able to directly track\nthe quantity or nature of chatbot conversations.\nTwo recent papers do report statistics on chatbot conversations, classified in a variety of ways\n(Handa et al., 2025; Tomlinson et al., 2025). We build on this work in several respects. First, the pool\nof users on ChatGPT is far larger, meaning we expect our data to be a closer approximation to the\naverage chatbot user.4 Second, we use automated classifiers to report on the types of messages that\nusers send using new classification taxonomies relative to the existing literature. Third, we report the\ndiffusion of chatbot use across populations and the growth of different types of usage within cohorts.\nFourth, we use a secure data clean room protocol to analyze aggregated employment and education\ncategories for a sample of our users, lending new insights about differences in the types of messages\nsent by different groups while protecting user privacy.\nOur primary sample is a random selection of messages sent to ChatGPT on consumer plans (Free,\nPlus, Pro) between May 2024 and June 2025.5\nMessages from the user to chatbot are classified\nautomatically using a number of different taxonomies: whether the message is used for paid work,\nthe topic of conversation, and the type of interaction (asking, doing, or expressing), and the O*NET\ntask the user is performing. Each taxonomy is defined in a prompt passed to an LLM, allowing us to\nclassify messages without any human seeing them. We give the text of most prompts in Appendix A\nalong with details about how the prompts were validated in Appendix B.6 The classification pipeline is\nprotected by a series of privacy measures, detailed below, to ensure no leakage of sensitive information\nduring the automated analysis. In a secure data clean room, we relate taxonomies of messages to\naggregated employment and education categories.\nTable 1 shows the growth in total message volume for work and non-work usage. Both types of\n1Reuters (2025), Roth (2025)\n2Bick et al. (2024) report that 28% of US adults used ChatGPT in late 2024, higher than any other chatbot.\n3We use the term LLM loosely here and give more details in the following section.\n4Wiggers (2025) reports estimates that in April 2025 ChatGPT was receiving more than 10 times as many visitors\nas either Claude or Copilot.\n5Our sample includes the three consumer plans (Free, Plus, or Pro). OpenAI also offers a variety of other ChatGPT\nplans (Business fka. Teams, Enterprise, Education), which we do not include in our sample.\n6Our classifiers take into account not just the randomly-selected user message, but also a portion of the preceding\nmessages in that conversation.\n1'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='Month\nNon-Work (M)\n(%)\nWork (M)\n(%)\nTotal Messages (M)\nJun 2024\n238\n53%\n213\n47%\n451\nJun 2025\n1,911\n73%\n716\n27%\n2,627\nTable 1: ChatGPT daily message counts (millions), broken down by likely work-related or non-work-related.\nTotal daily counts are exact measurements of message volume from all consumer plans. Daily counts of work\nand non-work related messages are estimated by classifying a random sample of conversations from that day.\nSampling is done to exclude users who opt-out of sharing their messages for model training, users who self-\nreport their age as under 18, logged-out users, deleted conversations, and accounts which have been deactivated\nor banned (details available in Section 3). Reported values are 7-day averages (to smooth weekly fluctuation)\nending on the 26th of June 2024 and 26th of June 2025.\nmessages have grown continuously, but non-work messages have grown faster and now represent more\nthan 70% of all consumer ChatGPT messages. While most economic analysis of AI has focused on its\nimpact on productivity in paid work, the impact on activity outside of work (home production) is on a\nsimilar scale and possibly larger. The decrease in the share of work-related messages is primarily due to\nchanging usage within each cohort of users rather than a change in the composition of new ChatGPT\nusers. This finding is consistent with Collis and Brynjolfsson (2025), who use choice experiments to\nuncover willingness-to-pay for generative AI and estimate a consumer surplus of at least $97 billion\nin 2024 alone in the US.\nWe next report on a classification of messages using a taxonomy developed at OpenAI for un-\nderstanding product usage (“conversation classifier”). Nearly 80% of all ChatGPT usage falls into\nthree broad categories, which we call Practical Guidance, Seeking Information, and Writing. Practical\nGuidance is the most common use case and includes activities like tutoring and teaching, how-to\nadvice about a variety of topics, and creative ideation.7 Seeking Information includes searching for\ninformation about people, current events, products, and recipes, and appears to be a very close sub-\nstitute for web search. Writing includes the automated production of emails, documents and other\ncommunications, but also editing, critiquing, summarizing, and translating text provided by the user.\nWriting is the most common use case at work, accounting for 40% of work-related messages on average\nin June 2025. About two-thirds of all Writing messages ask ChatGPT to modify user text (editing,\ncritiquing, translating, etc.) rather than creating new text from scratch. About 10% of all messages\nare requests for tutoring or teaching, suggesting that education is a key use case for ChatGPT.\nTwo of our findings stand in contrast to other work. First, we find the share of messages related\nto computer coding is relatively small: only 4.2% of ChatGPT messages are related to computer\nprogramming, compared to 33% of work-related Claude conversations Handa et al. (2025).8 Second, we\nfind the share of messages related to companionship or social-emotional issues is fairly small: only 1.9%\nof ChatGPT messages are on the topic of Relationships and Personal Reflection and 0.4% are related\n7The difference between Practical Guidance and Seeking Information is that the former is highly customized to the\nuser and can be adapted based on conversation and follow-up, whereas the latter is factual information that should be\nthe same for all users. For example, users interested in running might ask ChatGPT for the Boston Marathon qualifying\ntimes by age and gender (Seeking Information), or they might ask for a customized workout plan that matches their\ngoals and current level of fitness (Practical Guidance).\n8Handa et al. (2025) report that 37% of conversations are mapped to a “computer and mathematical” occupation\ncategory, and their Figure 12 shows 30% or more of all imputed tasks are programming or IT-related. We believe the\ndiscrepancy is partly due to the difference in types of users between Claude and ChatGPT, additionally Handa et al.\n(2025) only includes queries that ”possibly involve an occupational task”.\n2'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 4}, page_content='to Games and Role Play. In contrast, Zao-Sanders (2025) estimates that Therapy/Companionship is\nthe most prevalent use case for generative AI.9\nWe also document several important facts about demographic variation in ChatGPT usage. First,\nwe show evidence that the gender gap in ChatGPT usage has likely narrowed considerably over time,\nand may have closed completely. In the few months after ChatGPT was released about 80% of active\nusers had typically masculine first names.10 However, that number declined to 48% as of June 2025,\nwith active users slightly more likely to have typically feminine first names. Second, we find that\nnearly half of all messages sent by adults were sent by users under the age of 26, although age gaps\nhave narrowed somewhat in recent months. Third, we find that ChatGPT usage has grown relatively\nfaster in low- and middle-income countries over the last year. Fourth, we find that educated users and\nusers in highly-paid professional occupations are substantially more likely to use ChatGPT for work.\nWe introduce a new taxonomy to classify messages according to the kind of output the user is\nseeking, using a simple rubric that we call Asking, Doing, or Expressing.11\nAsking is when the\nuser is seeking information or clarification to inform a decision, corresponding to problem-solving\nmodels of knowledge work (e.g., Garicano (2000); Garicano and Rossi-Hansberg (2006); Carnehl and\nSchneider (2025); Ide and Talamas (2025)). Doing is when the user wants to produce some output\nor perform a particular task, corresponding to classic task-based models of work (e.g., Autor et al.\n(2003)). Expressing is when the user is expressing views or feelings but not seeking any information or\naction. We estimate that about 49% of messages are Asking, 40% are Doing, and 11% are Expressing.\nHowever, as of July 2025 about 56% of work-related messages are classified as Doing (e.g., performing\njob tasks), and nearly three-quarters of those are Writing tasks. The relative frequency of writing-\nrelated conversations is notable for two reasons. First, writing is a task that is common to nearly all\nwhite-collar jobs, and good written communication skills are among the top “soft” skills demanded by\nemployers (National Association of Colleges and Employers, 2024). Second, one distinctive feature of\ngenerative AI, relative to other information technologies, is its ability to produce long-form outputs\nsuch as writing and software code.\nWe also map message content to work activities using the Occupational Information Network\n(O*NET), a survey of job characteristics supported by the U.S. Department of Labor. We find that\nabout 81% of work-related messages are associated with two broad work activities: 1) obtaining,\ndocumenting, and interpreting information; and 2) making decisions, giving advice, solving problems,\nand thinking creatively. Additionally, we find that the work activities associated with ChatGPT usage\nare highly similar across very different kinds of occupations. For example, the work activities Getting\nInformation and Making Decisions and Solving Problems are in the top five of message frequency in\nnearly all occupations, ranging from management and business to STEM to administrative and sales\noccupations.\nOverall, we find that information-seeking and decision support are the most common ChatGPT\nuse cases in most jobs. This is consistent with the fact that almost half of all ChatGPT usage is\neither Practical Guidance or Seeking Information. We also show that Asking is growing faster than\n9Zao-Sanders (2025) is based on a manual collection and labeling of online resources (Reddit, Quora, online articles),\nand so we believe it likely resulted in an unrepresentative distribution of use cases.\n10Among those with names commonly associated with a particular gender.\n11Appendix A gives the full prompt text and Appendix B gives detail about how the prompts were validated against\npublic conversation data.\n3'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "

In [2]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=750, chunk_overlap=100)
split_docs = text_splitter.split_documents(docs)

print(split_docs)

len(split_docs)

[Document(metadata={'producer': '', 'creator': 'Microsoft Word', 'creationdate': '2025-10-17T19:51:23+00:00', 'source': 'data/rag-test.pdf', 'file_path': 'data/rag-test.pdf', 'total_pages': 1, 'format': 'PDF 1.7', 'title': '', 'author': 'Amit Shrigondekar', 'subject': '', 'keywords': '', 'moddate': '2025-10-17T19:51:23+00:00', 'trapped': '', 'modDate': "D:20251017195123+00'00'", 'creationDate': "D:20251017195123+00'00'", 'page': 0}, page_content='This is a text to prove that RAG works.  \nAmit Shrigondekar is the full stack engineer. His skills are backend specifically in node, \njava, bash , Kubernetes etc. \nAmit likes to spend time building things that automates boring repetitive error-prone \ntedious work so that it can be done efficiently. \nAmit does not like to be told details on how he need to perform his role at work. Amit likes \nto explore, design, research himself to figure out the right way to architect and build things.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 0}, page_content='NBER WORKING PAPER SERIES\nHOW PEOPLE USE CHATGPT\nAaron Chatterji\nThomas Cunningham\nDavid J. Deming\nZoe Hitzig\nChristopher Ong\nCarl Yan Shan\nKevin Wadman\nWorking Paper 34255\nhttp://www.nber.org/papers/w34255\nNATIONAL BUREAU OF ECONOMIC RESEARCH\n1050 Massachusetts Avenue\nCambridge, MA 02138\nSeptember 2025\nWe acknowledge help and comments from Joshua Achiam, Hemanth Asirvatham, Ryan \nBeiermeister, Rachel Brown, Cassandra Duchan Solis, Jason Kwon, Elliott Mokski, Kevin Rao, \nHarrison Satcher, Gawesha Weeratunga, Hannah Wong, and Analytics & Insights team. We \nespecially thank Tyna Eloundou and Pamela Mishkin who in several ways laid the foundation for \nthis work. This study was approved by Harvard IRB (IRB25-0983). A repository containing all'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 0}, page_content='this work. This study was approved by Harvard IRB (IRB25-0983). A repository containing all \ncode run to produce the analyses in this paper is available on request. The views expressed herein \nare those of the authors and do not necessarily reflect the views of the National Bureau of \nEconomic Research.\nAt least one co-author has disclosed additional relationships of potential relevance for this research. \nFurther information is available online at http://www.nber.org/papers/w34255\nNBER working papers are circulated for discussion and comment purposes. They have not been \npeer-reviewed or been subject to the review by the NBER Board of Directors that accompanies \nofficial NBER publications.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 0}, page_content='official NBER publications.\n© 2025 by Aaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, \nCarl Yan Shan, and Kevin Wadman. All rights reserved. Short sections of text, not to exceed two \nparagraphs, may be quoted without explicit permission provided that full credit, including © \nnotice, is given to the source.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='How People Use ChatGPT\nAaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, Carl\nYan Shan, and Kevin Wadman\nNBER Working Paper No. 34255\nSeptember 2025\nJEL No. J01, O3, O4\nABSTRACT\nDespite the rapid adoption of LLM chatbots, little is known about how they are used. We \ndocument the growth of ChatGPT’s consumer product from its launch in November 2022 \nthrough July 2025, when it had been adopted by around 10% of the world’s adult population. \nEarly adopters were disproportionately male but the gender gap has narrowed dramatically, and \nwe find higher growth rates in lower-income countries. Using a privacy-preserving automated'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='we find higher growth rates in lower-income countries. Using a privacy-preserving automated \npipeline, we classify usage patterns within a representative sample of ChatGPT conversations. \nWe find steady growth in work-related messages but even faster growth in non-work-related \nmessages, which have grown from 53% to more than 70% of all usage. Work usage is more \ncommon for educated users in highly-paid professional occupations. We classify messages by \nconversation topic and find that “Practical Guidance,” “Seeking Information,” and “Writing” are \nthe three most common topics and collectively account for nearly 80% of all conversations. \nWriting dominates work-related tasks, highlighting chatbots’ unique ability to generate digital'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='Writing dominates work-related tasks, highlighting chatbots’ unique ability to generate digital \noutputs compared to traditional search engines. Computer programming and self-expression both \nrepresent relatively small shares of use. Overall, we find that ChatGPT provides economic value \nthrough decision support, which is especially important in knowledge-intensive jobs.\nAaron Chatterji\nDuke University\nFuqua School of Business \nand OpenAI\nronnie@duke.edu\nThomas Cunningham \nOpenAI\ntom.cunningham@gmail.com\nDavid J. Deming\nHarvard University\nHarvard Kennedy School \nand NBER\ndavid_deming@harvard.edu\nZoe Hitzig\nOpenAI\nand Harvard Society of Fellows\nzhitzig@g.harvard.edu\nChristopher Ong\nHarvard University\nand OpenAI'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 1}, page_content='and Harvard Society of Fellows\nzhitzig@g.harvard.edu\nChristopher Ong\nHarvard University\nand OpenAI\nchristopherong@hks.harvard.edu\nCarl Yan Shan\nOpenAI\ncshan@openai.com\nKevin Wadman\nOpenAI\nkevin.wadman@c-openai.com'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='1\nIntroduction\nChatGPT launched in November 2022. By July 2025, 18 billion messages were being sent each week\nby 700 million users, representing around 10% of the global adult population.1 For a new technology,\nthis speed of global diffusion has no precedent (Bick et al., 2024).\nThis paper studies consumer usage of ChatGPT, the first mass-market chatbot and likely the\nlargest.2 ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence (AI)\ndeveloped over the last decade and generally considered to represent an acceleration in AI capabilities.3\nThe sudden growth in LLM abilities and adoption has intensified interest in the effects of artificial'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='intelligence on economic growth (Acemoglu, 2024; Korinek and Suh, 2024); employment (Eloundou\net al., 2025); and society (Kulveit et al., 2025). However, despite the rapid adoption of LLMs, there\nis limited public information on how they are used. A number of surveys have measured self-reported\nadoption of LLMs (Bick et al., 2024; Pew Research Center, 2025); however there are reasons to expect\nbias in self-reports (Ling and Imas, 2025), and none of these papers have been able to directly track\nthe quantity or nature of chatbot conversations.\nTwo recent papers do report statistics on chatbot conversations, classified in a variety of ways\n(Handa et al., 2025; Tomlinson et al., 2025). We build on this work in several respects. First, the pool'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='of users on ChatGPT is far larger, meaning we expect our data to be a closer approximation to the\naverage chatbot user.4 Second, we use automated classifiers to report on the types of messages that\nusers send using new classification taxonomies relative to the existing literature. Third, we report the\ndiffusion of chatbot use across populations and the growth of different types of usage within cohorts.\nFourth, we use a secure data clean room protocol to analyze aggregated employment and education\ncategories for a sample of our users, lending new insights about differences in the types of messages\nsent by different groups while protecting user privacy.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='sent by different groups while protecting user privacy.\nOur primary sample is a random selection of messages sent to ChatGPT on consumer plans (Free,\nPlus, Pro) between May 2024 and June 2025.5\nMessages from the user to chatbot are classified\nautomatically using a number of different taxonomies: whether the message is used for paid work,\nthe topic of conversation, and the type of interaction (asking, doing, or expressing), and the O*NET\ntask the user is performing. Each taxonomy is defined in a prompt passed to an LLM, allowing us to\nclassify messages without any human seeing them. We give the text of most prompts in Appendix A\nalong with details about how the prompts were validated in Appendix B.6 The classification pipeline is'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='protected by a series of privacy measures, detailed below, to ensure no leakage of sensitive information\nduring the automated analysis. In a secure data clean room, we relate taxonomies of messages to\naggregated employment and education categories.\nTable 1 shows the growth in total message volume for work and non-work usage. Both types of\n1Reuters (2025), Roth (2025)\n2Bick et al. (2024) report that 28% of US adults used ChatGPT in late 2024, higher than any other chatbot.\n3We use the term LLM loosely here and give more details in the following section.\n4Wiggers (2025) reports estimates that in April 2025 ChatGPT was receiving more than 10 times as many visitors\nas either Claude or Copilot.'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 2}, page_content='as either Claude or Copilot.\n5Our sample includes the three consumer plans (Free, Plus, or Pro). OpenAI also offers a variety of other ChatGPT\nplans (Business fka. Teams, Enterprise, Education), which we do not include in our sample.\n6Our classifiers take into account not just the randomly-selected user message, but also a portion of the preceding\nmessages in that conversation.\n1'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='Month\nNon-Work (M)\n(%)\nWork (M)\n(%)\nTotal Messages (M)\nJun 2024\n238\n53%\n213\n47%\n451\nJun 2025\n1,911\n73%\n716\n27%\n2,627\nTable 1: ChatGPT daily message counts (millions), broken down by likely work-related or non-work-related.\nTotal daily counts are exact measurements of message volume from all consumer plans. Daily counts of work\nand non-work related messages are estimated by classifying a random sample of conversations from that day.\nSampling is done to exclude users who opt-out of sharing their messages for model training, users who self-\nreport their age as under 18, logged-out users, deleted conversations, and accounts which have been deactivated'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='or banned (details available in Section 3). Reported values are 7-day averages (to smooth weekly fluctuation)\nending on the 26th of June 2024 and 26th of June 2025.\nmessages have grown continuously, but non-work messages have grown faster and now represent more\nthan 70% of all consumer ChatGPT messages. While most economic analysis of AI has focused on its\nimpact on productivity in paid work, the impact on activity outside of work (home production) is on a\nsimilar scale and possibly larger. The decrease in the share of work-related messages is primarily due to\nchanging usage within each cohort of users rather than a change in the composition of new ChatGPT'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 3}, page_content='changing usage within each cohort of users rather than a change in the composition of new ChatGPT\nusers. This finding is consistent with Collis and Brynjolfsson (2025), who use choice experiments to\nuncover willingness-to-pay for generative AI and estimate a consumer surplus of at least $97 billion\nin 2024 alone in the US.\nWe next report on a classification of messages using a taxonomy developed at OpenAI for un-\nderstanding product usage (“conversation classifier”). Nearly 80% of all ChatGPT usage falls into\nthree broad categories, which we call Practical Guidance, Seeking Information, and Writing. Practical\nGuidance is the most common use case and includes activities like tutoring and teaching, how-to'), Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source

201

# Create embeddings

In [3]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

In [4]:
# create Qdrant Vector Store
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance,VectorParams

client = QdrantClient(":memory:")

client.create_collection(
    collection_name="rag_collection_name",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

vector_store = QdrantVectorStore(
    client=client,
    collection_name="rag_collection_name",
    embedding=embeddings,
)

In [5]:
# Add documents to the vector store
vector_store.add_documents(documents=split_docs)

['319e4a87c21c42c5b8fb58f556269a95',
 'e53980120caa48b98351ff6183c8c0c6',
 '074babffe1c3461491b6af9682be20b6',
 '23708b8d2bcb45eb923519cc44afda33',
 'dc1b013d9cc345a091abede13952e497',
 '6cb1fab1977948c79c48c26285a00741',
 'e15ecd04fb09453ca7a334d024e8af70',
 '3fb2ae500eca4171a51de88828537e1c',
 '231e1b688ba34968ac172e0b0a58eb62',
 '4d17fb9b70a74c0f9b1c0ae14ccc510b',
 '8cb98f3a547c48c497bbbc294feacc29',
 '91c02d62597049389dd74efdf4fa0f73',
 '4f86ac47bf1043259bfb02d4359820d9',
 '76ec0c446f474929a5f7c6ad0b00be12',
 'c70c76ab5a9b4d47b6dae1c2537246a4',
 'fba9586a105f450fbf4ee097161119f7',
 '3ce3142e255a492ea27cfc50d5789a74',
 'c9ec6c0e1dba4987bb43b3eba0c63cfc',
 'dc6ebc4382bf4c6a93e69bda6e548cca',
 '67b59701af3f498997c7cb05a2a9269d',
 '9bdb1f3c851b402c800e2881e8b0b412',
 '843905aa2083414a990c2bf170f0c99b',
 '3c7eedae1c0c4a0c8e6d6577775d9197',
 'be9be9c86ab64e14b5146a046afa4b9c',
 'd580d7a31af04e7fbd71d989a130d8b9',
 '7eefb6b3646a402283175039e9ca31f5',
 '78740f1a2b2f4af481b6a4e48fe3d420',
 '5cfeedded9af4be89a276f4a6bae907c',
 '22023c30a48f4db0879ec35258f763b7',
 '58d51e21fb4b4edb8f4e7f24d916b1ee',
 '74cd2cecfbef44e689dbb27720a7f3d0',
 '41432c7d658d4139a5ce5128378d625c',
 '7df034a0c79c4b709f028972543db10d',
 '50d95ef2024d4ddaaa0c371fdd55472f',
 '83b50fae00b84659b9068a4c1a421f00',
 '2094b3f3f101401c9aed842af29bd0fc',
 'da6290deb82444a3947fb1ca34739a79',
 'bb30e397df64484690664e13e87fe824',
 '2fafb09449914d1aba50d4fbccdd71e2',
 'f3ec8cf09d274b01a442e1d3c2644ef3',
 'c03b1707e2884d7492605ba101bcf8f9',
 '898f515bb42345058b035b2b0b758ee2',
 'acb777575fee46e59172b1dd07cf4eba',
 '81c880924f9f42efa21abcadd7ea79eb',
 '286cf7b1c3cc4ea3919ca89068ea6766',
 'f3b300dcdcbc4d0b826876cfcddc7f8b',
 '917154ee8c4c43119500f403c9716bd2',
 '319cfdc3680b4d66baf954bbea0372ea',
 '1a6c1071d667414bbda8191b8738d657',
 '909e5234653d45578aa8b8dd28f3b5b2',
 '63e82d328914494098bb55f7c216dd68',
 '9df9e917968949a08f54aeae40f2b50b',
 'fe81234221214f7692b71a928540c5d8',
 '10b43faabf5c432c9f7346ce1ae2cbd5',
 '71086bbc936444bb9ccc2996499df87c',
 'f37f60e16f124416a651055e3cec3fbc',
 '0706911c77d1462c8852a73d554a328c',
 '9aadaa117c2143498eda3e114fd5ab25',
 'a83d8ef904454b56bc804fbbdddb6ac0',
 '5bbea2af246842e8a6db0ff1ae010a0a',
 'cf66daf184b44c0a923a7aab5919cee8',
 '6b9a6fe2f4724e47981516f66fe0e088',
 'b1d4175e49ff45f58c7fba2c0afd0f00',
 '15227504551945669a1fe8715d86fd55',
 '6c9090161d8149519d62b86e014b979f',
 'bdea204c3b294d7caf55a032d37a7e3d',
 '20a05891290f44e88603f3b7a06fb0d1',
 '22fb9b6ff8114396bf33fe20015d037d',
 'e5293b32477a4f8999d3172c7f217365',
 '366a51c2c24f4d0595bf3aee090486d1',
 'a72b1f87521141828fa336a239142c03',
 'c68fbcd864b14e3dabc5b637a805e9a7',
 '1ee6ea0919fb4dc9985eba7d7c3aef1d',
 'c6354ae624e84d7da17dae095a885e2c',
 '2e0f5c3b03934e39b8642739bc6508ae',
 '99d7ced1fcdb42b6802da9bf411c5a3f',
 '825965268d77431795982b563bd53fc5',
 '3597b62cee1141299c262cf668471977',
 '447dd848c4ed4b6d9d867b4963abf289',
 '0b64902a8e7447dda3e484796c966dde',
 '735406d9a8ec4a019be7c97198826466',
 '51ae6f35c9d144ddab3d8e526b1cd173',
 '70fa701a1ec74fc2afe5497e7b35f307',
 '6ef5b05fffaa4845987af6259e7207a1',
 '4d1f9a0632ee42d08cb6ecf5ae850290',
 '52b4a420f1f14fcab346b1ad596d46a9',
 'ff37ded6c4884babaa41cb0f15426b83',
 'f93c60daa057489c9410ab3dd3eb5059',
 '1bc6904a26b447a1a6bb29d08eb6488f',
 '2011587fb5704a228f2e2d0eedb47e45',
 '76833efb966646bb8db892ce14412b75',
 'cff3774d51bf464aa9e7aeda0367b5c7',
 '7fcc74003a1b48dd9768ed1442fbe96b',
 'c47953dd2126414196e5cca19cc31223',
 '35f159c537f9461d9185dc4041f550b2',
 'cdf40e65caf349c9a6656405b787568c',
 '9d9237141aaa439489455bdb7a135733',
 '47d6f315da7547e8ae9ac124b2fc8598',
 'e6304bad52de407bb3dff8469fbfefb4',
 '300ef983bdcf493cba364790baa197c9',
 '60820cc037114be6a035a121acac023a',
 'a8184b021b074b76bae78f53420056f3',
 '78557da303134d018af5d16f709ece6a',
 '2056bfc22b3542c7a743ec9b3fee45d9',
 '61e5247fdadf4f018edd16579d6013bf',
 '67ad6acd714a4e06868fe042f6030a89',
 '50a9c8b82ccd413e88b26eafa29873ab',
 'ba0c067f1f2b46cbbb8897a03a25995b',
 'f01b01b9e66b41408edf195fb6ffcc62',
 '29e3b002fbb04758b401f41c8d3aef94',
 '2b8a6fd55de34a3b8f91159dc5ef7420',
 '8535beff070d4789a4130e0e28340458',
 '86465ea9a7134ed082f51e05ab1518e7',
 '2660231df274440091b09ea09666aaa8',
 '0d07b526a03f434ba2ae11a611667fe6',
 '2be84cd42f474091ac07bb2f98e41452',
 '19e7cb45625346d89b4354a0f47333f1',
 '9a095456a9e443f881acd3849512eed7',
 '7902fef6d92a419da7cb2c2dbd7e92f0',
 'e6c6a38be4084505b9a38a783cbed35b',
 'b37b00d586f346e5b92d4b21de71adf7',
 'bf33822bd2b94fbe8e8e80b0b4cf4d2e',
 '2963a9abab254780b44ace7ece9f9be1',
 '4467b5cacc5b43ee857cba1a4fb409c3',
 'd6060880195945ae8f5ae300f906f755',
 'a9e72bc2750f48fa97a0a4750319c2d8',
 '39aef7f088f7487098bf6ba8c1a5d077',
 '4400cba0527e4856af6a232bb9352215',
 '2888be66e7f64566adca0f532839a007',
 '488e5bed175b4944a9aa8d3f2ab427ba',
 '715bf653a1f44128b9acef0f7ae38680',
 'e3952a78ebda4025a76a3afd43b8a928',
 '5a0f2ecc4b35493b933a9622674f14b3',
 '9ab66228d6074a7c926dc5a45d3b6156',
 'f7106b25187b4cc4a14e28b1097b92af',
 '345c421d2fab4ae597274e3a404a23eb',
 '71734d7cb1d04c6bb5c50772e3521e8b',
 'f36e8b43aca2402f9eaf2c7f51452d2d',
 '083f61f0fa214f07978a8a796256ae07',
 'fc56952d261846209ed039cbc7594657',
 'f03f6dcaafaa4bb6ba8233b48e7d4d09',
 '88b0cecc01bb4047812bd1666a0be0e0',
 'aafad8e06f6e477ea4966eee1a315c71',
 'e2f5d2b302274ba9992706b37c7c48c4',
 '5f425896b41a47a18787db4e52fca96e',
 'd8df84007df444ffa7620c99df379de9',
 '5b0ee5ee610e488c91d613ce880444a3',
 'abbde09d22b345b5be27eb50ea4c2f50',
 '9bd0a8d612ad42f4a2de43a9148a33c4',
 '1cd18f324a7f4cc59a215fbe6fde8729',
 'bee29ccecb6b48acbbffbaf55d7b216c',
 '6991760ed4c945b289143b52ba9286bd',
 'c8c1dbc8af9449d6b2d744ba3df40e93',
 'ec2624ba6e6740359df67766b65da5c2',
 '4d350ef4825d4746ac340cc9ca6866f0',
 'f195926b5f6848c7a3f274070283bb10',
 'c193c361184b406ea9328e6e078718bb',
 'bdce6c97d7e341ad9fdfc88af616d76d',
 '479156d577db40e2a9a2fc6115b90a60',
 'ff6fdacde9c44625beb122714b8be68e',
 'accfad3430a444e4a1563bcc014fbebe',
 'e7aedb3dee5242308a45b526b788317c',
 '10a4b926a397495599bbba4175223ed1',
 '6030d76504434d03abc311dd12023844',
 '47949c2e007940bdbfa7d7d4951e4b47',
 '51077f3b32ee43a7b1aad451a3711c45',
 '321ab755e0ec43579afcfb180498a12f',
 '9204ffd2638c40ddb47d905441ca5fc6',
 '36874f8903564d558a2ce26ba5144c48',
 '37bd91853d1f41d19ea25495d6fa798a',
 '0d33027a2faf4cffa00e70f264689fe2',
 'c2cc7752c5c54710ae45765ca366fe88',
 '0687217493f74d37ade53ebfe5b56160',
 '3a3ed0365ce346d996482555da66c837',
 '6c7d8f869c9b4f298963a44fa66850a6',
 '62d2c6cbd966499bb19354b42c444c5d',
 'cdb622d9fd7c4e5f86e331eb6523a463',
 '3cbd7c86205c423eba2989399ab28687',
 '22045f09e238469b8a9781f291cf003a',
 'b33caf5809ca4404b419339805281ab3',
 'b15924fed55b43548d26418fbb034a3e',
 '4716c2dda9aa4cceb0a465d19f9cac93',
 '2b5b7341b8ab4846abe5fa2cbddb6f0f',
 'a300cacf251a46819a116f872ef5309f',
 'ed443286e380469ba47db783caaf545c',
 'd30a8056725946c2a3f61e4e3e19ee54',
 '957253d28aef41fb9eb64dcc243aa97a',
 '7dbb3b03ca94408bbcf3ca4b59ebcc7d',
 'cd1becb8128c4b3daa819df0fc8583ba',
 'd5fd232507bc4cb1ac12eed89ed1ffb5',
 '0b3c65390f464ef8871bd58503c95b93',
 '4b5b6baf40cb40219c8a89074692896a',
 '4f4738cddc7d42caa0230c95c5cd8b7c',
 'a99f4e32adce47bd81fa1335e718c7f2',
 '2392aa7c5a54403fa9ddd45d3a943acf',
 '05e898036b0142acb022bf970ce858f3',
 'cac7421736fd43eeaae733ad695f95eb',
 'c0c68d4a077d4b7f88ced55ebc809e91',
 'fa77992ddff44a2283c99f720aa789dc',
 'fb674ae91159434ba5b7d665b76f93de',
 '6bffd65e40e54915b067af366894c128']

In [6]:
# Lets create a retriever
retriever = vector_store.as_retriever(search_kwargs={"k": 5})

In [7]:
retriever.invoke("what is the main purpose of the document?")

[Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 21, '_id': '7fcc74003a1b48dd9768ed1442fbe96b', '_collection_name': 'rag_collection_name'}, page_content='at work appears to be focused on two broad functions: 1) obtaining, documenting, and interpreting\ninformation; and 2) making decisions, giving advice, solving problems, and thinking creatively.\n20'),
 Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 45, '_id': '10a4b926a397495599bbba4175223ed1', '_collection_name': 'rag_collection_name'}, page_content='If the conversation has multiple distinct capabilities, choose the one that is the\nmost relevant to the **LAST message** in the conversation.\n,→\nExamples:\n**edit_or_critique_provided_text**:\n- "Help me improve my essay, including improving flow and correcting grammar\nerrors."\n,→\n- "Please shorten this paragraph."\n- "Can you proofread my article for grammatical mistakes?"\n- "Here’s my draft speech; can you suggest enhancements?"\n- "Stp aide moi `a corriger ma dissertation."\n**argument_or_summary_generation**:\n- "Make an argument for why the national debt is important."\n- "Write a three-paragraph essay about Abraham Lincoln."\n- "Summarize the Book of Matthew."\n- "Provide a summary of the theory of relativity."'),
 Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 21, '_id': 'cff3774d51bf464aa9e7aeda0367b5c7', '_collection_name': 'rag_collection_name'}, page_content='all messages.\nFigure 15 presents the distribution of GWAs for the subsample of messages we classify as work-\nrelated.\nAmong work-related messages, the most common GWAs are Documenting/Recording In-\nformation (18.4%), Making Decisions and Solving Problems (14.9%), Thinking Creatively (13.0%),\nWorking with Computers (10.8%), Interpreting the Meaning of Information for Others (10.1%), Get-\nting Information (9.3%), and Providing Consultation and Advice to Others (4.4%). These seven GWAs\ncollectively account for nearly 81% of work-related messages. Overall, the majority of ChatGPT usage\nat work appears to be focused on two broad functions: 1) obtaining, documenting, and interpreting'),
 Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 36, '_id': '2888be66e7f64566adca0f532839a007', '_collection_name': 'rag_collection_name'}, page_content='Occupation Group\nDocumenting/\nRecording\nInformation\nMaking\nDecisions\nAnd Solving\nProblems\nThinking\nCreatively\nWorking\nWith\nComputers\nInterpreting\nThe Meaning\nOf\nInformation\nFor Others\nGetting\nInformation\nProviding\nConsultation\nAnd Advice\nTo Others\nManagement\n2\n1\n3\n6\n4\n5\n8\nBusiness\n2\n1\n3\n6\n4\n5\n7\nComputer/Math\n4\n2\n5\n1\n3\n6\n7\nEngineering\n3\n1\n5\n2\n4\n6\n7\nScience\n2\n1\n4\n3\n6\n5\n7\nSocial Service\n2\n1\n3\nX\n5\n4\nX\nLegal\n1\nX\nX\nX\nX\nX\nX\nEducation\n1\n2\n3\n4\n6\n5\n7\nArts/Design/Media\n2\n1\n3\n5\n4\n6\n7\nHealth Professionals\n1\n2\n3\nX\n5\n4\n6\nFood Service\n1\nX\nX\nX\nX\nX\nX\nPersonal Service\n1\n2\n3\nX\n4\n5\nX\nSales\n2\n1\n3\n6\n4\n5\n7\nAdministrative\n2\n1\n3\n7\n4\n5\n8\nTransportation\n2\n1\n3\nX\nX\n4\nX\nMilitary\n2\n1\nX\nX\nX\nX\nX'),
 Document(metadata={'producer': 'macOS Version 15.4.1 (Build 24E263) Quartz PDFContext, AppendMode 1.1', 'creator': 'LaTeX with hyperref', 'creationdate': '2025-09-12T20:05:32+00:00', 'source': 'data/howpeopleuseai.pdf', 'file_path': 'data/howpeopleuseai.pdf', 'total_pages': 64, 'format': 'PDF 1.6', 'title': 'How People Use ChatGPT', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2025-09-15T10:32:36-04:00', 'trapped': '', 'modDate': "D:20250915103236-04'00'", 'creationDate': 'D:20250912200532Z', 'page': 63, '_id': 'fa77992ddff44a2283c99f720aa789dc', '_collection_name': 'rag_collection_name'}, page_content='Occupation Group\nDocumenting/\nRecording\nInformation\nMaking\nDecisions\nAnd Solving\nProblems\nThinking\nCreatively\nWorking\nWith\nComputers\nInterpreting\nThe Meaning\nOf\nInformation\nFor Others\nGetting\nInformation\nProviding\nConsultation\nAnd Advice\nTo Others\nManagement\n3\n2\n4\n7\n5\n1\n6\nBusiness\n3\n2\n6\n7\n4\n1\n5\nComputer/Math\n5\n4\n6\n1\n3\n2\n7\nEngineering\n5\n3\n7\n4\n2\n1\n6\nScience\n2\n3\n6\n7\n4\n1\n5\nSocial Service\n2\n3\n6\nX\n4\n1\n5\nLegal\n2\n3\n6\nX\n4\n1\n5\nEducation\n1\n3\n4\n7\n5\n2\n6\nArts/Design/Media\n2\n3\n4\n7\n5\n1\n6\nHealth Professionals\n2\n5\n6\nX\n4\n1\n3\nHealth Support\n2\n3\n6\nX\n4\n1\n5\nProtective Service\n2\nX\nX\nX\nX\n1\nX\nFood Service\n3\n5\n6\nX\n2\n1\n4\nPersonal Service\n2\n3\n5\nX\n4\n1\n6\nSales\n2\n5\n6\n7\n3\n1\n4\nAdministrative\n2\n4\n6\n8\n3\n1\n5\nConstruction\nX\nX\nX\nX\nX\n1\nX\nInstallation/Repair\nX\nX\nX\nX\nX\n1\nX')]

In [8]:
# produce node for the retrieval
def retrieve(state):
    retrieved_docs = retriever.invoke(state["question"])
    return {"context": retrieved_docs}

In [9]:
from langchain.prompts import ChatPromptTemplate

RAG_PROMPT = """\
    You are a helpful assistant who can answer questions based on the following context only:
    If you cannot answer the question based on the context - you must say "I don't know".
    
    ### Context: 
    {context}
    
    ### Question: 
    {question}
"""

rag_prompt = ChatPromptTemplate.from_template(RAG_PROMPT)

In [10]:
# Create LLM instance
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser


llm = ChatOpenAI(model="gpt-4.1-mini")

In [11]:
# Create a generator

def generate(state):
    docs_content="\n\n".join( doc.page_content for doc in state["context"])
    message = rag_prompt.format_messages(question=state["question"], context=docs_content)
    response = llm.invoke(message)
    return {"response": response.content}

In [12]:
# build a state 
from typing_extensions import TypedDict, List
from langchain_core.documents import Document

class State(TypedDict):
    question: str
    context: List[Document]
    response: str

In [13]:
# Lets build a graph 
from langgraph.graph import START,StateGraph

# 
graph_builder = StateGraph(State).add_sequence([retrieve, generate])
graph_builder.add_edge(START, "retrieve")
graph=graph_builder.compile()

In [14]:
# Run the graph
response = graph.invoke({"question": "who is Amit Shrigondekar?"})

print(response["response"])

Amit Shrigondekar is a full stack engineer with skills in backend development, specifically in node, java, bash, Kubernetes, etc. He likes to spend time building things that automate boring, repetitive, error-prone, and tedious work to make it more efficient. Amit does not like to be told details on how to perform his role at work; instead, he prefers to explore, design, and research himself to figure out the right way to architect and build things.

In [15]:
# Lets create some tools 

from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_community.tools.arxiv.tool import ArxivQueryRun

arxiv_tool = ArxivQueryRun()
tavily_tool = TavilySearchResults(max_results=5)

/var/folders/0j/52nrhqqd6hq140jsz5rrd5km0000gq/T/ipykernel_49193/2375597365.py:7: LangChainDeprecationWarning: The class `TavilySearchResults` was deprecated in LangChain 0.3.25 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-tavily package and should be used instead. To use it run `pip install -U :class:`~langchain-tavily` and import as `from :class:`~langchain_tavily import TavilySearch``.
  tavily_tool = TavilySearchResults(max_results=5)

## ⚠️ Critical Fix: ai_rag_tool Now Returns Contexts

**Problem**: The original `ai_rag_tool` only returned the final answer, throwing away the retrieved document chunks.

**Solution**: Modified to return JSON with BOTH:
- `answer`: The generated response
- `contexts`: List of retrieved document chunks

This allows RAGAS to evaluate whether the answer is grounded in the retrieved contexts.

In [ ]:
# lets create a tool for the graph  
from langchain_core.tools import tool
import json

@tool
def ai_rag_tool(question: str):
    """
    Use this tool to answer questions based on the context provided. Input should be a fully formed question.
    """
    
    response = graph.invoke({"question": question})
    
    # Return BOTH the answer AND the retrieved contexts
    # Format: JSON string with answer and contexts
    result = {
        "answer": response["response"],
        "contexts": [doc.page_content for doc in response["context"]]
    }
    
    return json.dumps(result)

In [ ]:
# Test the updated ai_rag_tool to verify it returns contexts
test_result = ai_rag_tool.invoke({"question": "Who is Amit Shrigondekar?"})
print("Tool result:", test_result[:200], "...")

# Parse it to see the structure
import json
parsed = json.loads(test_result)
print("\nParsed structure:")
print(f"- answer: {parsed['answer'][:100]}...")
print(f"- contexts: {len(parsed['contexts'])} chunks retrieved")
print(f"- First context: {parsed['contexts'][0][:100]}...")

In [17]:
# lets create a tool belt

tools = [ai_rag_tool, arxiv_tool, tavily_tool]

In [18]:
# Bind tools to the llm
from langchain_openai import ChatOpenAI

model = ChatOpenAI(model="gpt-4.1",temperature=0)
model=model.bind_tools(tools)

model.invoke("who is Amit Shrigondekar?")

AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_5Wn0U99h9VYwovESsu9oVF2i', 'function': {'arguments': '{"question":"Who is Amit Shrigondekar?"}', 'name': 'ai_rag_tool'}, 'type': 'function'}], 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 23, 'prompt_tokens': 197, 'total_tokens': 220, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4.1-2025-04-14', 'system_fingerprint': 'fp_422e2d36a8', 'id': 'chatcmpl-CRmlyTKpJWhvpVmHnVsjlq1eFXnHP', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run--3e7a0d12-9ccb-4002-94d2-50bffc70a74f-0', tool_calls=[{'name': 'ai_rag_tool', 'args': {'question': 'Who is Amit Shrigondekar?'}, 'id': 'call_5Wn0U99h9VYwovESsu9oVF2i', 'type': 'tool_call'}], usage_metadata={'input_tokens': 197, 'output_tokens': 23, 'total_tokens': 220, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

In [19]:
# Langgraph Agent

from typing import TypedDict, Annotated,List
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    messages:Annotated[list,add_messages]
    context:List[Document]

In [20]:
from langgraph.prebuilt import ToolNode

def call_model(state):
    messages = state["messages"]
    response = model.invoke(messages)
    return {"messages": [response]}

tool_node = ToolNode(tools)

In [21]:
from langgraph.graph import StateGraph,END

uncompiled_graph= StateGraph(AgentState)
uncompiled_graph.add_node("agent",call_model)
uncompiled_graph.add_node("action",tool_node)

In [22]:
# add function/runnable for the conditional edge

def should_continue(state):
    last_message=state["messages"][-1]
    if last_message.tool_calls:
        return "action"
    return END 


uncompiled_graph.set_entry_point("agent")
uncompiled_graph.add_conditional_edges(
    "agent", should_continue
)
uncompiled_graph.add_edge("action","agent");

In [23]:
compiled_graph=uncompiled_graph.compile()

In [24]:
# Run the graph
from langchain_core.messages import HumanMessage

inputs={"messages":[HumanMessage(content="who is Amit Shrigondekar?")]}

async for chunk in compiled_graph.astream(inputs,stream_mode="updates"):
    for node,values in chunk.items():
        print("Receiving updates from node",node)
        print(values["messages"])
        print("\n\n")

Receiving updates from node agent
[AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_stVkNnbNqzVJpEbmzbn5DtUK', 'function': {'arguments': '{"question":"Who is Amit Shrigondekar?"}', 'name': 'ai_rag_tool'}, 'type': 'function'}], 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 23, 'prompt_tokens': 197, 'total_tokens': 220, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4.1-2025-04-14', 'system_fingerprint': 'fp_e24a1fec47', 'id': 'chatcmpl-CRmm0yU7fsuVupGFQaX7ye4qChQLg', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run--eb6121aa-55c3-460d-b0ba-7823a36f3ab3-0', tool_calls=[{'name': 'ai_rag_tool', 'args': {'question': 'Who is Amit Shrigondekar?'}, 'id': 'call_stVkNnbNqzVJpEbmzbn5DtUK', 'type': 'tool_call'}], usage_metadata={'input_tokens': 197, 'output_tokens': 23, 'total_tokens': 220, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]



Receiving updates from node action
[ToolMessage(content='Amit Shrigondekar is a full stack engineer with skills in backend development, specifically in Node, Java, Bash, Kubernetes, etc. He likes to spend time building things that automate boring, repetitive, error-prone, tedious work to make it more efficient. He does not like to be told details on how to perform his role at work and prefers to explore, design, and research by himself to figure out the right way to architect and build things.', name='ai_rag_tool', id='fd516b18-7852-4236-856f-4942dd538c50', tool_call_id='call_stVkNnbNqzVJpEbmzbn5DtUK')]



Receiving updates from node agent
[AIMessage(content='Amit Shrigondekar is a full stack engineer skilled in backend development, particularly with technologies like Node, Java, Bash, and Kubernetes. He enjoys building automation tools to make repetitive and tedious tasks more efficient. Amit prefers autonomy in his work, favoring independent exploration, design, and research to determine the best way to architect and build solutions.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 71, 'prompt_tokens': 323, 'total_tokens': 394, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4.1-2025-04-14', 'system_fingerprint': 'fp_422e2d36a8', 'id': 'chatcmpl-CRmm58BPIifmOPVv9Bo3sntjcttL7', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='run--1062fdb9-55be-42a9-a34f-5fa7067904a9-0', usage_metadata={'input_tokens': 323, 'output_tokens': 71, 'total_tokens': 394, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]

# Ragas Baseline And SDG

In [25]:
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings

generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

In [27]:
from ragas.testset import TestsetGenerator

generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)

dataset = generator.generate_with_langchain_docs(docs, testset_size=10)

Applying HeadlinesExtractor:   0%|          | 0/21 [00:00<?, ?it/s]

Applying HeadlineSplitter:   0%|          | 0/65 [00:00<?, ?it/s]

unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node
unable to apply transformation: 'headlines' property not found in this node

Applying SummaryExtractor:   0%|          | 0/40 [00:00<?, ?it/s]

Property 'summary' already exists in node 'fab977'. Skipping!
Property 'summary' already exists in node '612c9b'. Skipping!
Property 'summary' already exists in node '6e0974'. Skipping!
Property 'summary' already exists in node '159963'. Skipping!
Property 'summary' already exists in node 'eaa9c1'. Skipping!
Property 'summary' already exists in node 'ccc2fa'. Skipping!
Property 'summary' already exists in node 'b6f283'. Skipping!
Property 'summary' already exists in node '2f9748'. Skipping!
Property 'summary' already exists in node 'c5e9c6'. Skipping!
Property 'summary' already exists in node '703173'. Skipping!
Property 'summary' already exists in node '9194b6'. Skipping!
Property 'summary' already exists in node '8abd6a'. Skipping!
Property 'summary' already exists in node '68aaf9'. Skipping!
Property 'summary' already exists in node '5e82b7'. Skipping!
Property 'summary' already exists in node '3126b8'. Skipping!
Property 'summary' already exists in node 'eeacc9'. Skipping!
Property 'summary' already exists in node 'b59d56'. Skipping!
Property 'summary' already exists in node '7429eb'. Skipping!
Property 'summary' already exists in node '32da40'. Skipping!

Applying CustomNodeFilter:   0%|          | 0/4 [00:00<?, ?it/s]

Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/44 [00:00<?, ?it/s]

Property 'summary_embedding' already exists in node '612c9b'. Skipping!
Property 'summary_embedding' already exists in node 'eaa9c1'. Skipping!
Property 'summary_embedding' already exists in node '6e0974'. Skipping!
Property 'summary_embedding' already exists in node 'fab977'. Skipping!
Property 'summary_embedding' already exists in node 'ccc2fa'. Skipping!
Property 'summary_embedding' already exists in node 'b6f283'. Skipping!
Property 'summary_embedding' already exists in node '159963'. Skipping!
Property 'summary_embedding' already exists in node '9194b6'. Skipping!
Property 'summary_embedding' already exists in node 'c5e9c6'. Skipping!
Property 'summary_embedding' already exists in node '68aaf9'. Skipping!
Property 'summary_embedding' already exists in node '8abd6a'. Skipping!
Property 'summary_embedding' already exists in node '5e82b7'. Skipping!
Property 'summary_embedding' already exists in node '2f9748'. Skipping!
Property 'summary_embedding' already exists in node '703173'. Skipping!
Property 'summary_embedding' already exists in node 'eeacc9'. Skipping!
Property 'summary_embedding' already exists in node '3126b8'. Skipping!
Property 'summary_embedding' already exists in node 'b59d56'. Skipping!
Property 'summary_embedding' already exists in node '32da40'. Skipping!
Property 'summary_embedding' already exists in node '7429eb'. Skipping!

Applying [CosineSimilarityBuilder, OverlapScoreBuilder]:   0%|          | 0/2 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/12 [00:00<?, ?it/s]

In [28]:
dataset.to_pandas()

                                           user_input  ...                      synthesizer_name
0   How has Artificial Intelligence contributed to...  ...  single_hop_specifc_query_synthesizer
1   how artificial intelligence like chatgpt grow ...  ...  single_hop_specifc_query_synthesizer
2   How is Generative AI like ChatGPT used in know...  ...  single_hop_specifc_query_synthesizer
3   What does Brynjolfsson estimate about the econ...  ...  single_hop_specifc_query_synthesizer
4   How did the rapid global diffusion of new tech...  ...  multi_hop_abstract_query_synthesizer
5   How do work-related versus non-work-related ch...  ...  multi_hop_abstract_query_synthesizer
6   How do the ChatGPT adoption and usage statisti...  ...  multi_hop_abstract_query_synthesizer
7   What do the ChatGPT adoption and usage statist...  ...  multi_hop_abstract_query_synthesizer
8   How did ChatGPT's user base and message volume...  ...  multi_hop_specific_query_synthesizer
9   Considering the rapid adoption of ChatGPT by 7...  ...  multi_hop_specific_query_synthesizer
10  how 700 million users send messages on chatgpt...  ...  multi_hop_specific_query_synthesizer
11  How did ChatGPT's user base and message volume...  ...  multi_hop_specific_query_synthesizer

[12 rows x 4 columns]

In [39]:
for test_row in dataset:
  inputs={"messages":[HumanMessage(content=test_row.eval_sample.user_input)]}
  response = compiled_graph.invoke(inputs)
  test_row.eval_sample.response = response["messages"][-1].content;
  # test_row.eval_sample.retrieved_contexts = [context.page_content for context in response["context"]]

In [40]:
dataset.to_pandas()

                                           user_input  ...                      synthesizer_name
0   How has Artificial Intelligence contributed to...  ...  single_hop_specifc_query_synthesizer
1   how artificial intelligence like chatgpt grow ...  ...  single_hop_specifc_query_synthesizer
2   How is Generative AI like ChatGPT used in know...  ...  single_hop_specifc_query_synthesizer
3   What does Brynjolfsson estimate about the econ...  ...  single_hop_specifc_query_synthesizer
4   How did the rapid global diffusion of new tech...  ...  multi_hop_abstract_query_synthesizer
5   How do work-related versus non-work-related ch...  ...  multi_hop_abstract_query_synthesizer
6   How do the ChatGPT adoption and usage statisti...  ...  multi_hop_abstract_query_synthesizer
7   What do the ChatGPT adoption and usage statist...  ...  multi_hop_abstract_query_synthesizer
8   How did ChatGPT's user base and message volume...  ...  multi_hop_specific_query_synthesizer
9   Considering the rapid adoption of ChatGPT by 7...  ...  multi_hop_specific_query_synthesizer
10  how 700 million users send messages on chatgpt...  ...  multi_hop_specific_query_synthesizer
11  How did ChatGPT's user base and message volume...  ...  multi_hop_specific_query_synthesizer

[12 rows x 5 columns]

In [ ]:
import json
import re
from typing import Any, List, Dict, Optional

class ContextParser:
    """Parser to extract contexts from tool call results in agent messages."""
    
    @staticmethod
    def detect_tool_type(message: Any) -> Optional[str]:
        """Detect which tool was called based on the message."""
        try:
            # Check if message has tool_calls attribute
            if hasattr(message, 'tool_calls') and message.tool_calls:
                tool_name = message.tool_calls[0].get('name', '')
                if 'tavily' in tool_name.lower():
                    return 'tavily'
                elif 'arxiv' in tool_name.lower():
                    return 'arxiv'
                elif 'ai_rag' in tool_name.lower() or 'rag' in tool_name.lower():
                    return 'ai_rag'
            
            # Check if it's a ToolMessage with a name attribute
            if hasattr(message, 'name'):
                tool_name = message.name
                if 'tavily' in tool_name.lower():
                    return 'tavily'
                elif 'arxiv' in tool_name.lower():
                    return 'arxiv'
                elif 'ai_rag' in tool_name.lower() or 'rag' in tool_name.lower():
                    return 'ai_rag'
                    
        except Exception as e:
            print(f"Error detecting tool type: {e}")
        return None
    
    @staticmethod
    def extract_content(message: Any) -> Optional[str]:
        """Extract content from a message object."""
        try:
            if hasattr(message, 'content'):
                content = message.content
                if isinstance(content, str):
                    # Handle JSON-like strings with quotes
                    if content.startswith('content="') or content.startswith("content='"):
                        # Find the matching end quote by counting quotes
                        stack = []
                        in_quote = False
                        for i, char in enumerate(content):
                            if char == '"' and (i == 0 or content[i-1] != '\\'):
                                if not in_quote:
                                    stack.append(i)
                                    in_quote = True
                                else:
                                    stack.pop()
                                    if not stack and 'name=' in content[i:]:
                                        return content[8:i]  # 8 is len('content="')
                    return content
        except Exception as e:
            print(f"Error extracting content: {e}")
        return None
    
    @staticmethod
    def parse_tavily_results(content: str) -> List[Dict]:
        """Parse Tavily search results from content string."""
        try:
            # Parse the JSON string
            if isinstance(content, str):
                data = json.loads(content)
                
                # Get results array from the appropriate location
                if isinstance(data, list):
                    results = data
                elif isinstance(data, dict):
                    if 'artifact' in data and 'results' in data['artifact']:
                        results = data['artifact']['results']
                    elif 'results' in data:
                        results = data['results']
                    else:
                        results = []
                else:
                    results = []
                
                # Ensure content is string in each result
                for result in results:
                    if isinstance(result.get('content'), dict):
                        result['content'] = str(result['content'])
                        
                return results
        except Exception as e:
            print(f"Error parsing Tavily results: {str(e)}")
        return []
    
    @staticmethod
    def parse_ai_rag_results(content: str) -> List[Dict]:
        """Parse AI RAG tool results from content string."""
        try:
            # The ai_rag_tool now returns JSON with 'answer' and 'contexts'
            data = json.loads(content)
            
            # Extract contexts list
            if isinstance(data, dict) and 'contexts' in data:
                contexts = data['contexts']
                # Convert to list of dicts with 'content' key for consistency
                documents = [{'content': ctx} for ctx in contexts if ctx]
                return documents
            
            # Fallback: if it's just a plain string (old format)
            elif isinstance(content, str) and content.strip():
                return [{'content': content}]
            
            return []
        except json.JSONDecodeError:
            # If it's not JSON, treat it as plain text
            print("ai_rag content is not JSON, treating as plain text")
            return [{'content': content}] if content else []
        except Exception as e:
            print(f"Error parsing AI RAG results: {str(e)}")
            return []
    
    @staticmethod  
    def parse_arxiv_results(content: str) -> List[Dict]:
        """Parse arXiv results from content string."""
        try:
            papers = []
            # Split by "Published: " but keep the delimiter
            sections = re.split(r'(?=Published: )', content)
            
            for section in sections:
                if not section.strip():
                    continue
                
                # Extract paper details
                date_match = re.search(r'Published: (\d{4}-\d{2}-\d{2})', section)
                title_match = re.search(r'Title: (.*?)(?=\nAuthors:|$)', section, re.DOTALL)
                authors_match = re.search(r'Authors: (.*?)(?=\nSummary:|$)', section, re.DOTALL)
                summary_match = re.search(r'Summary: (.*?)(?=\n\nPublished:|$)', section, re.DOTALL)
                
                if date_match and title_match:
                    summary = summary_match.group(1).strip() if summary_match else ''
                    # Ensure summary is a string
                    if isinstance(summary, dict):
                        summary = str(summary)
                    
                    paper = {
                        'date': date_match.group(1),
                        'title': title_match.group(1).strip(),
                        'authors': authors_match.group(1).strip() if authors_match else '',
                        'summary': summary
                    }
                    papers.append(paper)
            
            return papers
        except Exception as e:
            print(f"Error parsing arXiv results: {str(e)}")
        return []


def parse_tool_call(message: Any) -> List[Dict]:
    """Parse tool call results from a conversation message."""
    parser = ContextParser()
    
    print("\n=== Starting message parsing ===")
    print(f"Message type: {type(message)}")
    
    # Detect tool type
    tool_type = parser.detect_tool_type(message)
    print(f"Detected tool type: {tool_type}")
    
    if tool_type is None:
        print("Could not detect tool type")
        return []
    
    # Extract content
    content = parser.extract_content(message)
    if content is None:
        print("Could not extract content")
        return []
    
    print(f"Extracted content type: {type(content)}")
    
    # Parse based on tool type
    if tool_type == 'tavily':
        results = parser.parse_tavily_results(content)
        print(f"Parsed {len(results)} Tavily results")
        return results
    elif tool_type == 'ai_rag':
        results = parser.parse_ai_rag_results(content)
        print(f"Parsed {len(results)} AI RAG results")
        return results
    elif tool_type == 'arxiv':
        results = parser.parse_arxiv_results(content)
        print(f"Parsed {len(results)} arXiv results")
        return results
    
    return []

In [44]:
def extract_contexts_from_messages(messages: List) -> List[str]:
    """
    Extract all contexts from a list of messages in a conversation.
    This looks for ToolMessage objects and parses their content.
    """
    all_contexts = []
    
    for message in messages:
        # Check if it's a ToolMessage (contains tool call results)
        if hasattr(message, 'name') and hasattr(message, 'content'):
            print(f"\nProcessing ToolMessage from {message.name}")
            
            # Parse the tool call results
            parsed_results = parse_tool_call(message)
            
            # Extract content from parsed results
            for result in parsed_results:
                if isinstance(result, dict):
                    # Different tools return different formats
                    if 'content' in result:
                        all_contexts.append(result['content'])
                    elif 'summary' in result:
                        all_contexts.append(result['summary'])
                    elif 'text' in result:
                        all_contexts.append(result['text'])
    
    return all_contexts


def get_contexts_from_graph_response(response: dict) -> List[str]:
    """
    Extract contexts from a graph response that contains messages.
    """
    if 'messages' not in response:
        print("No messages found in response")
        return []
    
    contexts = extract_contexts_from_messages(response['messages'])
    print(f"\nExtracted {len(contexts)} total contexts")
    return contexts

In [45]:
# Updated evaluation loop with context extraction
for test_row in dataset:
    inputs = {"messages": [HumanMessage(content=test_row.eval_sample.user_input)]}
    response = compiled_graph.invoke(inputs)
    
    # Extract the response text from the last message
    test_row.eval_sample.response = response["messages"][-1].content
    
    # Extract contexts from tool calls in the conversation
    retrieved_contexts = get_contexts_from_graph_response(response)
    
    # Store contexts for evaluation
    test_row.eval_sample.retrieved_contexts = retrieved_contexts
    
    print(f"Question: {test_row.eval_sample.user_input[:100]}...")
    print(f"Retrieved {len(retrieved_contexts)} contexts")
    print("-" * 50)

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 0 total contexts
Question: How has Artificial Intelligence contributed to the rapid adoption of ChatGPT?...
Retrieved 0 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 0 total contexts
Question: how artificial intelligence like chatgpt grow so fast and what it mean for work and economy from use...
Retrieved 0 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 0 total contexts
Question: How is Generative AI like ChatGPT used in knowledge-intensive jobs?...
Retrieved 0 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: What does Brynjolfsson estimate about the economic value of generative AI usage in the US?...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How did the rapid global diffusion of new technology contribute to the unprecedented growth and adop...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How do work-related versus non-work-related chatbot usage differ in terms of query types and growth ...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How do the ChatGPT adoption and usage statistics, including the rapid growth to 700 million users se...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: What do the ChatGPT adoption and usage statistics reveal about its rapid growth and the balance betw...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How did ChatGPT's user base and message volume evolve by July 2025, and what were the main differenc...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: Considering the rapid adoption of ChatGPT by 700 million users sending billions of messages weekly, ...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: how 700 million users send messages on chatgpt and what work and non work usage show about productiv...
Retrieved 5 contexts
--------------------------------------------------

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.human.HumanMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Error parsing Tavily results: Expecting value: line 1 column 1 (char 0)
Parsed 0 Tavily results

Processing ToolMessage from tavily_search_results_json

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.tool.ToolMessage'>
Detected tool type: tavily
Extracted content type: <class 'str'>
Parsed 5 Tavily results

Processing ToolMessage from None

=== Starting message parsing ===
Message type: <class 'langchain_core.messages.ai.AIMessage'>
Error detecting tool type: 'NoneType' object has no attribute 'lower'
Detected tool type: None
Could not detect tool type

Extracted 5 total contexts
Question: How did ChatGPT's user base and message volume evolve by July 2025, and what were the main trends in...
Retrieved 5 contexts
--------------------------------------------------

In [46]:
# Verify dataset is properly populated
df = dataset.to_pandas()
print("Dataset columns:", df.columns.tolist())
print("\nSample row check:")
sample = df.iloc[0]
print(f"- user_input: {type(sample['user_input'])} - {str(sample['user_input'])[:100]}...")
print(f"- response: {type(sample['response'])} - {str(sample['response'])[:100]}...")
print(f"- reference: {type(sample['reference'])} - {str(sample['reference'])[:100]}...")
print(f"- retrieved_contexts: {type(sample['retrieved_contexts'])} - Length: {len(sample['retrieved_contexts']) if sample['retrieved_contexts'] else 0}")

# Check if all required columns have data
print("\nData completeness check:")
print(f"- Rows with user_input: {df['user_input'].notna().sum()}/{len(df)}")
print(f"- Rows with response: {df['response'].notna().sum()}/{len(df)}")
print(f"- Rows with reference: {df['reference'].notna().sum()}/{len(df)}")
print(f"- Rows with retrieved_contexts: {df['retrieved_contexts'].notna().sum()}/{len(df)}")

Dataset columns: ['user_input', 'retrieved_contexts', 'reference_contexts', 'response', 'reference', 'synthesizer_name']

Sample row check:
- user_input: <class 'str'> - How has Artificial Intelligence contributed to the rapid adoption of ChatGPT?...
- response: <class 'str'> - Artificial Intelligence (AI) has played a central role in the rapid adoption of ChatGPT. Here are th...
- reference: <class 'str'> - ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence developed over t...
- retrieved_contexts: <class 'list'> - Length: 0

Data completeness check:
- Rows with user_input: 12/12
- Rows with response: 12/12
- Rows with reference: 12/12
- Rows with retrieved_contexts: 12/12

In [47]:
# Run RAGAS evaluation with properly populated dataset
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy, ContextEntityRecall, NoiseSensitivity
from ragas import evaluate, RunConfig
from ragas import EvaluationDataset
from ragas.llms import LangchainLLMWrapper

# Create evaluation dataset from pandas
evaluation_dataset = EvaluationDataset.from_pandas(dataset.to_pandas())

# Configure evaluation
custom_run_config = RunConfig(timeout=360)
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))

# Run evaluation with all metrics
baseline_result = evaluate(
    dataset=evaluation_dataset,
    metrics=[
        LLMContextRecall(),      # Requires: user_input, retrieved_contexts, reference
        Faithfulness(),          # Requires: user_input, response, retrieved_contexts
        FactualCorrectness(),    # Requires: user_input, response, reference
        ResponseRelevancy(),     # Requires: user_input, response
        ContextEntityRecall(),   # Requires: user_input, retrieved_contexts, reference
        NoiseSensitivity()       # Requires: user_input, retrieved_contexts
    ],
    llm=evaluator_llm,
    run_config=custom_run_config
)

# Display results
print("RAGAS Evaluation Results:")
print(baseline_result)

Evaluating:   0%|          | 0/72 [00:00<?, ?it/s]

Exception raised in Job[5]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[11]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[17]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[29]: TimeoutError()
Exception raised in Job[41]: TimeoutError()
Exception raised in Job[59]: TimeoutError()

RAGAS Evaluation Results:
{'context_recall': 0.4015, 'faithfulness': 0.6503, 'factual_correctness': 0.4383, 'answer_relevancy': 0.9589, 'context_entity_recall': 0.1602, 'noise_sensitivity_relevant': 0.3581}

In [48]:
print(baseline_result)

{'context_recall': 0.4015, 'faithfulness': 0.6503, 'factual_correctness': 0.4383, 'answer_relevancy': 0.9589, 'context_entity_recall': 0.1602, 'noise_sensitivity_relevant': 0.3581}

## Let us use Cohere's Rerank model for re-Evaluating

Now that we've got our baseline - let's make a change and see how the model improves or doesn't improve!

In [72]:
# Let us build the adjusted retriever using cohere's rerank model

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance,VectorParams
from langchain_openai import OpenAIEmbeddings

text_splitter = RecursiveCharacterTextSplitter(chunk_size=750, chunk_overlap=100)
split_docs = text_splitter.split_documents(docs)
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

client = QdrantClient(":memory:")
client.create_collection(
    collection_name="cohere_rag_collection",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

vector_store = QdrantVectorStore(
    client=client,
    collection_name="cohere_rag_collection",
    embedding=embeddings,
)
vector_store.add_documents(documents=split_docs)
cohere_retriever = vector_store.as_retriever(search_kwargs={"k": 20})


from langchain.retrievers.contextual_compression import ContextualCompressionRetriever
from langchain_cohere import CohereRerank

def cohere_adjusted_retriever(state):
  compressor = CohereRerank(model="rerank-v3.5",top_n=5)
  compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=cohere_retriever
  )
  retrieved_docs = compression_retriever.invoke(state["question"])
  return {"context" : retrieved_docs}



# Lets build a graph 
from langgraph.graph import START,StateGraph

# 
cohere_graph_builder = StateGraph(State).add_sequence([cohere_adjusted_retriever, generate])
cohere_graph_builder.add_edge(START, "cohere_adjusted_retriever")
cohere_graph=cohere_graph_builder.compile()

# lets create a tool for the graph  
from langchain_core.tools import tool
import json

@tool
def ai_rag_tool_cohere(question: str):
    """
    Use this tool to answer questions based on the context provided. Input should be a fully formed question.
    """
    
    response = cohere_graph.invoke({"question": question})
    
    # Return BOTH the answer AND the retrieved contexts
    # Format: JSON string with answer and contexts
    result = {
        "answer": response["response"],
        "contexts": [doc.page_content for doc in response["context"]]
    }
    
    return json.dumps(result)

tools_cohere = [ai_rag_tool_cohere, arxiv_tool, tavily_tool]

# Bind tools to the llm
from langchain_openai import ChatOpenAI

model = ChatOpenAI(model="gpt-4.1",temperature=0)
model=model.bind_tools(tools_cohere)


from langgraph.prebuilt import ToolNode

def call_model(state):
    messages = state["messages"]
    response = model.invoke(messages)
    return {"messages": [response]}

tool_node_cohere = ToolNode(tools_cohere)

from langgraph.graph import StateGraph,END

cohere_uncompiled_graph= StateGraph(AgentState)
cohere_uncompiled_graph.add_node("agent",call_model)
cohere_uncompiled_graph.add_node("action",tool_node_cohere)

def should_continue(state):
    last_message=state["messages"][-1]
    if last_message.tool_calls:
        return "action"
    return END 


cohere_uncompiled_graph.set_entry_point("agent")
cohere_uncompiled_graph.add_conditional_edges(
    "agent", should_continue
)
cohere_uncompiled_graph.add_edge("action","agent");

cohere_compiled_graph=cohere_uncompiled_graph.compile()

# Run the graph
from langchain_core.messages import HumanMessage

inputs={"messages":[HumanMessage(content="who is Amit Shrigondekar?")]}

async for chunk in cohere_compiled_graph.astream(inputs,stream_mode="updates"):
    for node,values in chunk.items():
        print("Receiving updates from node",node)
        print(values["messages"])
        print("\n\n")

Receiving updates from node agent
[AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_m2ux53yAThfGE8KyZG1SKrFO', 'function': {'arguments': '{"query":"Amit Shrigondekar"}', 'name': 'tavily_search_results_json'}, 'type': 'function'}], 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 23, 'prompt_tokens': 198, 'total_tokens': 221, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4.1-2025-04-14', 'system_fingerprint': 'fp_564354cebb', 'id': 'chatcmpl-CSCV7Mt83JrkfPceehepFYM9uG18e', 'service_tier': 'default', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run--8b005d15-d3c5-48ee-9518-b6c82770c32d-0', tool_calls=[{'name': 'tavily_search_results_json', 'args': {'query': 'Amit Shrigondekar'}, 'id': 'call_m2ux53yAThfGE8KyZG1SKrFO', 'type': 'tool_call'}], usage_metadata={'input_tokens': 198, 'output_tokens': 23, 'total_tokens': 221, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]



Receiving updates from node action
[ToolMessage(content='[{"title": "Amit Shrigondekar - Salt Lake City, Utah | about.me", "url": "https://about.me/amitshrigondekar", "content": "Amit Shrigondekar. Software Engineer in Salt Lake City, Utah. Visit my website. Get a page and a domain with your name. Get started for free Get your page.", "score": 0.68697983}, {"title": "Senior Software Engineer - Amit Shrigondekar\'s Posts - Quora", "url": "https://hykguytxwprkzpbx.quora.com/about", "content": "Icon for Amit Shrigondekar\'s Posts. Follow. Amit Shrigondekar\'s Posts. 1 Contributor. Profile photo for Quora User.", "score": 0.49992734}, {"title": "90+ \\"Shrigondekar\\" profiles - LinkedIn", "url": "https://www.linkedin.com/pub/dir/+/Shrigondekar", "content": "View the profiles of professionals named \\"Shrigondekar\\" on LinkedIn. There are 90+ professionals named \\"Shrigondekar\\", who use LinkedIn to exchange", "score": 0.29552004}, {"title": "Patentee Index - Official Gazette for Patents | USPTO", "url": "https://patentsgazette.uspto.gov/week22/OG/patentee/alphaS.html", "content": "Watanabe, Yohei; Hara, Taeko; Suzuki, Yoshimi; Saito, Yuki; and Matsuki, Takahiro 12318416 Cl. A61K 35/745.\\n\\nSaitou, Yasushi: See--\\n\\nSugimoto, Shunichi; Hyon, Sang-Ho; Saitou, Yasushi; Kamikura, Sadayuki; and Fukuzawa, Yuji 12318930 Cl. B25J 9/106.\\n\\nSajid, Haseeb; and Malik, Hassan Sterilization cassette D1078084 Cl. D24‑217.\\n\\nSajja, Sai Krishna; Shrigondekar, Anish; and Stojanovski, Igor Generating and storing aggregate data slices in a remote shared storage system 12321396 Cl. G06F 16/906. [...] Yu, Philip Leung Ho; Chiu, Keith; Yuen, Man Fung; and Seto, Wai Kay Walter 12322151 Cl. G06V 10/454.\\n\\nSettima Meccanica S.r.l.: See--\\n\\nRossi, Manuele 12320355 Cl. F04C 2/165.\\n\\nSeuferer, Kelly; to QBP, LLC Candy mold D1077592 Cl. D7‑675.\\n\\nSeutter, Sean M.: See--\\n\\nPanavalappil Kumarankutty, Hanish Kumar; Seutter, Sean M.; Gondhalekar, Sudhir R.; Boyd, Jr., Wendell Glenn; Ramamurthi, Badri; Athani, Shekhar; Kalal, Anil Kumar; and Pinson, II, Jay Dee 12322633 Cl. H01L 21/6833. [...] SAMSUNG ELECTRONICS CO., LTD.: See--\\n\\nAgiwal, Anil; Ingale, Mangesh Abhimanyu; and Jin, Seungri 12323904 Cl. H04W 48/16.\\n\\nAn, Jungchul; Ryu, Kwanghee; and Oh, Myeongsu 12322858 Cl. H01Q 1/243.\\n\\nBae, Seungjae; Baek, Moohyun; Yang, Soonwoong; Lee, Changmin; and Choi, Jongchul 12324090 Cl. H05K 1/0243.\\n\\nBae, Su Young; Park, Jong Ho; Lee, Dong Soo; and Kim, Wan Don 12324233 Cl. H10D 84/85.\\n\\nBaek, Kiwon 12322687 Cl. H01L 23/49822.\\n\\nBharitkar, Sunil 12323780 Cl. H04R 3/04.", "score": 0.2946821}, {"title": "Onkar Bhat - Veeam Software - LinkedIn", "url": "https://www.linkedin.com/in/onkarbhat", "content": "## People Also Viewed\\n- Priyesh Lakar (None) - \\n- Kumar Ritesh Ranjan Sinha (None) - \\n- Navaneeth Krishnan (None) - \\n- Soham Kulkarni (None) - \\n- Yu Tian (None) - \\n- Sayali Kajale (None) - \\n- Manasa Pola (None) - \\n- Shiwei(George) Huang (None) - \\n- Sachin Magar (None) - \\n- Xiaosong Lu (Software Development Engineer Happy to refer tech roles at Amazon Studios) - \\n- Akshay Mishra (None) - \\n- Junior Quintero (None) - \\n- Kun Qian (None) - \\n- Devashish Nyati (None) - \\n- Xin Yao (None) - [...] ## Honors & Awards\\nN/A\\n\\n## Certifications\\nN/A\\n\\n## Volunteering\\nN/A\\n\\n## Languages\\nEnglish (-), Kannada (-), Hindi (-), Tulu (-)\\n\\n## Organizations\\nN/A\\n\\n## Activity\\nN/A [...] - Jeevan Hunsur Eswara (None) - \\n- Qiao Yang (As a senior ML Engineer , I am an enthusiastic, self-motivated, reliable, responsible and hard working person open to new opportunities.) - \\n- Joey Wang (Senior System Software Engineer at NVIDIA) - \\n- Keith Chirayus (None) - \\n- Harsh Kumar (None) -", "score": 0.061791133}]', name='tavily_search_results_json', id='7a8e4868-fa3f-4303-9c5a-fd852448782a', tool_call_id='call_m2ux53yAThfGE8KyZG1SKrFO', artifact={'query': 'Amit Shrigondekar', 'follow_up_questions': None, 'answer': None, 'images': [], 'results': [{'url': 'https://about.me/amitshrigondekar', 'title': 'Amit Shrigondekar - Salt Lake City, Utah | about.me', 'content': 'Amit Shrigondekar. Software Engineer in Salt Lake City, Utah. Visit my website. Get a page and a domain with your name. Get started for free Get your page.', 'score': 0.68697983, 'raw_content': None}, {'url': 'https://hykguytxwprkzpbx.quora.com/about', 'title': "Senior Software Engineer - Amit Shrigondekar's Posts - Quora", 'content': "Icon for Amit Shrigondekar's Posts. Follow. Amit Shrigondekar's Posts. 1 Contributor. Profile photo for Quora User.", 'score': 0.49992734, 'raw_content': None}, {'url': 'https://www.linkedin.com/pub/dir/+/Shrigondekar', 'title': '90+ "Shrigondekar" profiles - LinkedIn', 'content': 'View the profiles of professionals named "Shrigondekar" on LinkedIn. There are 90+ professionals named "Shrigondekar", who use LinkedIn to exchange', 'score': 0.29552004, 'raw_content': None}, {'url': 'https://patentsgazette.uspto.gov/week22/OG/patentee/alphaS.html', 'title': 'Patentee Index - Official Gazette for Patents | USPTO', 'content': 'Watanabe, Yohei; Hara, Taeko; Suzuki, Yoshimi; Saito, Yuki; and Matsuki, Takahiro 12318416 Cl. A61K 35/745.\n\nSaitou, Yasushi: See--\n\nSugimoto, Shunichi; Hyon, Sang-Ho; Saitou, Yasushi; Kamikura, Sadayuki; and Fukuzawa, Yuji 12318930 Cl. B25J 9/106.\n\nSajid, Haseeb; and Malik, Hassan Sterilization cassette D1078084 Cl. D24‑217.\n\nSajja, Sai Krishna; Shrigondekar, Anish; and Stojanovski, Igor Generating and storing aggregate data slices in a remote shared storage system 12321396 Cl. G06F 16/906. [...] Yu, Philip Leung Ho; Chiu, Keith; Yuen, Man Fung; and Seto, Wai Kay Walter 12322151 Cl. G06V 10/454.\n\nSettima Meccanica S.r.l.: See--\n\nRossi, Manuele 12320355 Cl. F04C 2/165.\n\nSeuferer, Kelly; to QBP, LLC Candy mold D1077592 Cl. D7‑675.\n\nSeutter, Sean M.: See--\n\nPanavalappil Kumarankutty, Hanish Kumar; Seutter, Sean M.; Gondhalekar, Sudhir R.; Boyd, Jr., Wendell Glenn; Ramamurthi, Badri; Athani, Shekhar; Kalal, Anil Kumar; and Pinson, II, Jay Dee 12322633 Cl. H01L 21/6833. [...] SAMSUNG ELECTRONICS CO., LTD.: See--\n\nAgiwal, Anil; Ingale, Mangesh Abhimanyu; and Jin, Seungri 12323904 Cl. H04W 48/16.\n\nAn, Jungchul; Ryu, Kwanghee; and Oh, Myeongsu 12322858 Cl. H01Q 1/243.\n\nBae, Seungjae; Baek, Moohyun; Yang, Soonwoong; Lee, Changmin; and Choi, Jongchul 12324090 Cl. H05K 1/0243.\n\nBae, Su Young; Park, Jong Ho; Lee, Dong Soo; and Kim, Wan Don 12324233 Cl. H10D 84/85.\n\nBaek, Kiwon 12322687 Cl. H01L 23/49822.\n\nBharitkar, Sunil 12323780 Cl. H04R 3/04.', 'score': 0.2946821, 'raw_content': None}, {'url': 'https://www.linkedin.com/in/onkarbhat', 'title': 'Onkar Bhat - Veeam Software - LinkedIn', 'content': '## People Also Viewed\n- Priyesh Lakar (None) - \n- Kumar Ritesh Ranjan Sinha (None) - \n- Navaneeth Krishnan (None) - \n- Soham Kulkarni (None) - \n- Yu Tian (None) - \n- Sayali Kajale (None) - \n- Manasa Pola (None) - \n- Shiwei(George) Huang (None) - \n- Sachin Magar (None) - \n- Xiaosong Lu (Software Development Engineer Happy to refer tech roles at Amazon Studios) - \n- Akshay Mishra (None) - \n- Junior Quintero (None) - \n- Kun Qian (None) - \n- Devashish Nyati (None) - \n- Xin Yao (None) - [...] ## Honors & Awards\nN/A\n\n## Certifications\nN/A\n\n## Volunteering\nN/A\n\n## Languages\nEnglish (-), Kannada (-), Hindi (-), Tulu (-)\n\n## Organizations\nN/A\n\n## Activity\nN/A [...] - Jeevan Hunsur Eswara (None) - \n- Qiao Yang (As a senior ML Engineer , I am an enthusiastic, self-motivated, reliable, responsible and hard working person open to new opportunities.) - \n- Joey Wang (Senior System Software Engineer at NVIDIA) - \n- Keith Chirayus (None) - \n- Harsh Kumar (None) -', 'score': 0.061791133, 'raw_content': None}], 'response_time': 1.86, 'request_id': '4123a3df-fabc-4e46-9c56-e61764042b40'})]



Receiving updates from node agent
[AIMessage(content='Amit Shrigondekar is a software engineer based in Salt Lake City, Utah. There is limited public information available about him, but he appears to have a professional presence online, including a personal website. If you need more specific details about his career or background, please let me know!', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 60, 'prompt_tokens': 1526, 'total_tokens': 1586, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4.1-2025-04-14', 'system_fingerprint': 'fp_564354cebb', 'id': 'chatcmpl-CSCVA7jgr5F4SuoPVSHuWK9pl89CP', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='run--faf2145a-536a-4446-a98a-0b3c35b96081-0', usage_metadata={'input_tokens': 1526, 'output_tokens': 60, 'total_tokens': 1586, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]

In [ ]:
# import time
# import copy

# rerank_dataset = copy.deepcopy(dataset)

# # Updated evaluation loop with context extraction
# for test_row in rerank_dataset:
#     inputs = {"messages": [HumanMessage(content=test_row.eval_sample.user_input)]}
#     response = cohere_compiled_graph.invoke(inputs)
    
#     # Extract the response text from the last message
#     test_row.eval_sample.response = response["messages"][-1].content
    
#     # Extract contexts from tool calls in the conversation
#     retrieved_contexts = get_contexts_from_graph_response(response)
    
#     # Store contexts for evaluation
#     test_row.eval_sample.retrieved_contexts = retrieved_contexts
    
#     print(f"Question: {test_row.eval_sample.user_input[:100]}...")
#     print(f"Retrieved {len(retrieved_contexts)} contexts")
#     print("-" * 50)
#     time.sleep(2) # To try to avoid rate limiting.

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [ ]:
import time
import copy

rerank_dataset = copy.deepcopy(dataset)

# Updated evaluation loop with context extraction
for test_row in rerank_dataset:
    inputs = {"messages": [HumanMessage(content=test_row.eval_sample.user_input)]}
    response = cohere_compiled_graph.invoke(inputs)
    
    # DEBUG: Print which tools were called
    print(f"\n=== Question: {test_row.eval_sample.user_input[:80]}... ===")
    for msg in response["messages"]:
        if hasattr(msg, 'tool_calls') and msg.tool_calls:
            for tool_call in msg.tool_calls:
                print(f"Tool called: {tool_call.get('name', 'unknown')}")
        if hasattr(msg, 'name') and msg.name:
            print(f"Tool response from: {msg.name}")
    
    # Extract the response text from the last message
    test_row.eval_sample.response = response["messages"][-1].content
    
    # Extract contexts from tool calls in the conversation
    retrieved_contexts = get_contexts_from_graph_response(response)
    
    # Store contexts for evaluation
    test_row.eval_sample.retrieved_contexts = retrieved_contexts
    
    print(f"Retrieved {len(retrieved_contexts)} contexts")
    print("-" * 50)
    time.sleep(2)

In [74]:
# Test what ai_rag_tool_cohere actually returns
test_result = ai_rag_tool_cohere.invoke({"question": "What is ChatGPT?"})
print("=== RAW TOOL OUTPUT ===")
print(f"Type: {type(test_result)}")
print(f"Content: {test_result}")
print("\n=== TRYING TO PARSE AS JSON ===")
try:
    import json
    parsed = json.loads(test_result)
    print(f"Parsed successfully: {parsed}")
    print(f"Has 'contexts' key: {'contexts' in parsed}")
    if 'contexts' in parsed:
        print(f"Number of contexts: {len(parsed['contexts'])}")
        print(f"First context: {parsed['contexts'][0][:100] if parsed['contexts'] else 'EMPTY'}")
except Exception as e:
    print(f"ERROR: {e}")

=== RAW TOOL OUTPUT ===
Type: <class 'str'>
Content: {"answer": "ChatGPT is the first mass-market chatbot and likely the largest, based on a Large Language Model (LLM), a type of Artificial Intelligence (AI) developed over the last decade that represents an acceleration in AI capabilities. It allows users to submit plain-text messages (\"prompts\") and returns generated text-based responses. While additional features like web search and image generation exist, the most typical interaction remains the exchange of text messages. ChatGPT is used widely for producing writing, software code, spreadsheets, and other digital products, providing customized responses and novel content generation that distinguish it from traditional web search engines.", "contexts": ["1\nIntroduction\nChatGPT launched in November 2022. By July 2025, 18 billion messages were being sent each week\nby 700 million users, representing around 10% of the global adult population.1 For a new technology,\nthis speed of global diffusion has no precedent (Bick et al., 2024).\nThis paper studies consumer usage of ChatGPT, the first mass-market chatbot and likely the\nlargest.2 ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence (AI)\ndeveloped over the last decade and generally considered to represent an acceleration in AI capabilities.3\nThe sudden growth in LLM abilities and adoption has intensified interest in the effects of artificial", "maximize the \u201cquality\u201d of that response, where the quality is measured with a variety of metrics.\nIn a prototypical interaction, a user submits a plain-text message (\u201cprompt\u201d) and ChatGPT\nreturns the message (\u201cresponse\u201d) generated from an underlying LLM. A large set of additional features\nhave been added to ChatGPT\u2014including the possibility for the LLM to search the web or external\ndatabases, and generate images based on text\u2014but the exchange of text-based messages remains the\nmost typical interaction.\nSince its launch ChatGPT has used a variety of different underlying LLMs e.g., GPT-3.5, GPT-4,\nGPT-4o, o1, o3, and GPT-5.12 In addition there are occasional updates to the model\u2019s weights and", "Writing dominates work-related tasks, highlighting chatbots\u2019 unique ability to generate digital \noutputs compared to traditional search engines. Computer programming and self-expression both \nrepresent relatively small shares of use. Overall, we find that ChatGPT provides economic value \nthrough decision support, which is especially important in knowledge-intensive jobs.\nAaron Chatterji\nDuke University\nFuqua School of Business \nand OpenAI\nronnie@duke.edu\nThomas Cunningham \nOpenAI\ntom.cunningham@gmail.com\nDavid J. Deming\nHarvard University\nHarvard Kennedy School \nand NBER\ndavid_deming@harvard.edu\nZoe Hitzig\nOpenAI\nand Harvard Society of Fellows\nzhitzig@g.harvard.edu\nChristopher Ong\nHarvard University\nand OpenAI", "(0.4%).\nWhile users can seek information and advice from traditional web search engines as well as from\nChatGPT, the ability to produce writing, software code, spreadsheets, and other digital products\ndistinguishes generative AI from existing technologies.\nChatGPT is also more flexible than web\nsearch even for traditional applications like Seeking Information and Practical Guidance, because\nusers receive customized responses (e.g., tailored workout plans, new product ideas, ideas for fantasy\nfootball team names) that represent newly generated content or novel modification of user-provided\ncontent and follow-up requests.\nFigure 9: Breakdown of granular conversation topic shares within the coarse mapping defined in Table 3. The", "How People Use ChatGPT\nAaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, Carl\nYan Shan, and Kevin Wadman\nNBER Working Paper No. 34255\nSeptember 2025\nJEL No. J01, O3, O4\nABSTRACT\nDespite the rapid adoption of LLM chatbots, little is known about how they are used. We \ndocument the growth of ChatGPT\u2019s consumer product from its launch in November 2022 \nthrough July 2025, when it had been adopted by around 10% of the world\u2019s adult population. \nEarly adopters were disproportionately male but the gender gap has narrowed dramatically, and \nwe find higher growth rates in lower-income countries. Using a privacy-preserving automated"]}

=== TRYING TO PARSE AS JSON ===
Parsed successfully: {'answer': 'ChatGPT is the first mass-market chatbot and likely the largest, based on a Large Language Model (LLM), a type of Artificial Intelligence (AI) developed over the last decade that represents an acceleration in AI capabilities. It allows users to submit plain-text messages ("prompts") and returns generated text-based responses. While additional features like web search and image generation exist, the most typical interaction remains the exchange of text messages. ChatGPT is used widely for producing writing, software code, spreadsheets, and other digital products, providing customized responses and novel content generation that distinguish it from traditional web search engines.', 'contexts': ['1\nIntroduction\nChatGPT launched in November 2022. By July 2025, 18 billion messages were being sent each week\nby 700 million users, representing around 10% of the global adult population.1 For a new technology,\nthis speed of global diffusion has no precedent (Bick et al., 2024).\nThis paper studies consumer usage of ChatGPT, the first mass-market chatbot and likely the\nlargest.2 ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence (AI)\ndeveloped over the last decade and generally considered to represent an acceleration in AI capabilities.3\nThe sudden growth in LLM abilities and adoption has intensified interest in the effects of artificial', 'maximize the “quality” of that response, where the quality is measured with a variety of metrics.\nIn a prototypical interaction, a user submits a plain-text message (“prompt”) and ChatGPT\nreturns the message (“response”) generated from an underlying LLM. A large set of additional features\nhave been added to ChatGPT—including the possibility for the LLM to search the web or external\ndatabases, and generate images based on text—but the exchange of text-based messages remains the\nmost typical interaction.\nSince its launch ChatGPT has used a variety of different underlying LLMs e.g., GPT-3.5, GPT-4,\nGPT-4o, o1, o3, and GPT-5.12 In addition there are occasional updates to the model’s weights and', 'Writing dominates work-related tasks, highlighting chatbots’ unique ability to generate digital \noutputs compared to traditional search engines. Computer programming and self-expression both \nrepresent relatively small shares of use. Overall, we find that ChatGPT provides economic value \nthrough decision support, which is especially important in knowledge-intensive jobs.\nAaron Chatterji\nDuke University\nFuqua School of Business \nand OpenAI\nronnie@duke.edu\nThomas Cunningham \nOpenAI\ntom.cunningham@gmail.com\nDavid J. Deming\nHarvard University\nHarvard Kennedy School \nand NBER\ndavid_deming@harvard.edu\nZoe Hitzig\nOpenAI\nand Harvard Society of Fellows\nzhitzig@g.harvard.edu\nChristopher Ong\nHarvard University\nand OpenAI', '(0.4%).\nWhile users can seek information and advice from traditional web search engines as well as from\nChatGPT, the ability to produce writing, software code, spreadsheets, and other digital products\ndistinguishes generative AI from existing technologies.\nChatGPT is also more flexible than web\nsearch even for traditional applications like Seeking Information and Practical Guidance, because\nusers receive customized responses (e.g., tailored workout plans, new product ideas, ideas for fantasy\nfootball team names) that represent newly generated content or novel modification of user-provided\ncontent and follow-up requests.\nFigure 9: Breakdown of granular conversation topic shares within the coarse mapping defined in Table 3. The', 'How People Use ChatGPT\nAaron Chatterji, Thomas Cunningham, David J. Deming, Zoe Hitzig, Christopher Ong, Carl\nYan Shan, and Kevin Wadman\nNBER Working Paper No. 34255\nSeptember 2025\nJEL No. J01, O3, O4\nABSTRACT\nDespite the rapid adoption of LLM chatbots, little is known about how they are used. We \ndocument the growth of ChatGPT’s consumer product from its launch in November 2022 \nthrough July 2025, when it had been adopted by around 10% of the world’s adult population. \nEarly adopters were disproportionately male but the gender gap has narrowed dramatically, and \nwe find higher growth rates in lower-income countries. Using a privacy-preserving automated']}
Has 'contexts' key: True
Number of contexts: 5
First context: 1
Introduction
ChatGPT launched in November 2022. By July 2025, 18 billion messages were being sent

In [76]:
# Verify dataset is properly populated
df = rerank_dataset.to_pandas()
print("Dataset columns:", df.columns.tolist())
print("\nSample row check:")
sample = df.iloc[0]
print(f"- user_input: {type(sample['user_input'])} - {str(sample['user_input'])[:100]}...")
print(f"- response: {type(sample['response'])} - {str(sample['response'])[:100]}...")
print(f"- reference: {type(sample['reference'])} - {str(sample['reference'])[:100]}...")
print(f"- retrieved_contexts: {type(sample['retrieved_contexts'])} - Length: {len(sample['retrieved_contexts']) if sample['retrieved_contexts'] else 0}")

# Check if all required columns have data
print("\nData completeness check:")
print(f"- Rows with user_input: {df['user_input'].notna().sum()}/{len(df)}")
print(f"- Rows with response: {df['response'].notna().sum()}/{len(df)}")
print(f"- Rows with reference: {df['reference'].notna().sum()}/{len(df)}")
print(f"- Rows with retrieved_contexts: {df['retrieved_contexts'].notna().sum()}/{len(df)}")

Dataset columns: ['user_input', 'retrieved_contexts', 'reference_contexts', 'response', 'reference', 'synthesizer_name']

Sample row check:
- user_input: <class 'str'> - How has Artificial Intelligence contributed to the rapid adoption of ChatGPT?...
- response: <class 'str'> - Artificial Intelligence (AI) has played a central role in the rapid adoption of ChatGPT, and its con...
- reference: <class 'str'> - ChatGPT is based on a Large Language Model (LLM), a type of Artificial Intelligence developed over t...
- retrieved_contexts: <class 'list'> - Length: 0

Data completeness check:
- Rows with user_input: 12/12
- Rows with response: 12/12
- Rows with reference: 12/12
- Rows with retrieved_contexts: 12/12

In [77]:
# Run RAGAS evaluation with properly populated dataset
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, ResponseRelevancy, ContextEntityRecall, NoiseSensitivity
from ragas import evaluate, RunConfig
from ragas import EvaluationDataset
from ragas.llms import LangchainLLMWrapper

# Create evaluation dataset from pandas
cohere_evaluation_dataset = EvaluationDataset.from_pandas(rerank_dataset.to_pandas())

# Configure evaluation
custom_run_config = RunConfig(timeout=360)
cohere_evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))

# Run evaluation with all metrics
cohere_rerank_result = evaluate(
    dataset=cohere_evaluation_dataset,
    metrics=[
        LLMContextRecall(),      # Requires: user_input, retrieved_contexts, reference
        Faithfulness(),          # Requires: user_input, response, retrieved_contexts
        FactualCorrectness(),    # Requires: user_input, response, reference
        ResponseRelevancy(),     # Requires: user_input, response
        ContextEntityRecall(),   # Requires: user_input, retrieved_contexts, reference
        NoiseSensitivity()       # Requires: user_input, retrieved_contexts
    ],
    llm=cohere_evaluator_llm,
    run_config=custom_run_config
)

# Display results
print("RAGAS Evaluation Results:")
print(cohere_rerank_result)

Evaluating:   0%|          | 0/72 [00:00<?, ?it/s]

Exception raised in Job[23]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[35]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[5]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[11]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[17]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[59]: ValueError(zero-size array to reduction operation maximum which has no identity)
Exception raised in Job[65]: TimeoutError()

RAGAS Evaluation Results:
{'context_recall': 0.2574, 'faithfulness': 0.4566, 'factual_correctness': 0.5017, 'answer_relevancy': 0.9563, 'context_entity_recall': 0.0807, 'noise_sensitivity_relevant': 0.4254}

In [78]:
print(cohere_rerank_result)

{'context_recall': 0.2574, 'faithfulness': 0.4566, 'factual_correctness': 0.5017, 'answer_relevancy': 0.9563, 'context_entity_recall': 0.0807, 'noise_sensitivity_relevant': 0.4254}

In [59]:
print(baseline_result)

{'context_recall': 0.4015, 'faithfulness': 0.6503, 'factual_correctness': 0.4383, 'answer_relevancy': 0.9589, 'context_entity_recall': 0.1602, 'noise_sensitivity_relevant': 0.3581}